/*
 * movie_rec.c - auto-generated by CHDK code_gen.
 */
#include "conf.h"

int *video_quality = &conf.video_quality;
int *video_mode    = &conf.video_mode;

long def_table[24]={0x2000, 0x38D, 0x788, 0x5800, 0x9C5, 0x14B8, 0x10000, 0x1C6A, 0x3C45, 0x8000, 0xE35, 0x1E23,
           0x1CCD, -0x2E1, -0x579, 0x4F33, -0x7EB, -0xF0C, 0xE666, -0x170A, -0x2BC6, 0x7333, -0xB85, -0x15E3};

long table[24];

void change_video_tables(int a, int b){
 int i;
 for (i=0;i<24;i++) table[i]=(def_table[i]*a)/b;
}

long CompressionRateTable[]={0x60, 0x5D, 0x5A, 0x57, 0x54, 0x51, 0x4D, 0x48, 0x42, 0x3B, 0x32, 0x29, 0x22, 0x1D, 0x17, 0x14, 0x10, 0xE, 0xB, 9, 7, 6, 5, 4, 3, 2, 1};

/*************************************************************/
//** movie_record_task @ 0xFFCF82B4 - 0xFFCF83B8, length=66
void __attribute__((naked,noinline)) movie_record_task() {
asm volatile (
"    STMFD   SP!, {R2-R8,LR} \n"
"    LDR     R7, =0x2710 \n"
"    LDR     R4, =0x5648 \n"
"    MOV     R6, #0 \n"
"    MOV     R5, #1 \n"

"loc_FFCF82C8:\n"
"    LDR     R0, [R4, #0x18] \n"
"    MOV     R2, #0 \n"
"    ADD     R1, SP, #4 \n"
"    BL      sub_FFC167B8 /*_ReceiveMessageQueue*/ \n"
"    LDR     R0, [R4, #0x20] \n"
"    CMP     R0, #0 \n"
"    BNE     loc_FFCF8398 \n"
"    LDR     R0, [SP, #4] \n"
"    LDR     R1, [R0] \n"
"    SUB     R1, R1, #2 \n"
"    CMP     R1, #9 \n"
"    ADDLS   PC, PC, R1, LSL#2 \n"
"    B       loc_FFCF8398 \n"
"    B       loc_FFCF834C \n"
"    B       loc_FFCF836C \n"
"    B       loc_FFCF837C \n"
"    B       loc_FFCF8384 \n"
"    B       loc_FFCF8354 \n"
"    B       loc_FFCF838C \n"
"    B       loc_FFCF835C \n"
"    B       loc_FFCF8398 \n"
"    B       loc_FFCF8394 \n"
"    B       loc_FFCF8324 \n"

"loc_FFCF8324:\n"
"    LDR     R0, =0xFFCF7FC0 \n"
"    STR     R6, [R4, #0x34] \n"
"    STR     R0, [R4, #0xA0] \n"
"    LDR     R0, =0xFFCF7A44 \n"
"    LDR     R2, =0xFFCF7960 \n"
"    LDR     R1, =0x294D0 \n"
"    STR     R6, [R4, #0x24] \n"
"    BL      sub_FFC96144 \n"
"    STR     R5, [R4, #0x38] \n"
"    B       loc_FFCF8398 \n"

"loc_FFCF834C:\n"
"    BL      unlock_optical_zoom\n" // added
"    BL      sub_FFCF80B8 \n"
"    B       loc_FFCF8398 \n"

"loc_FFCF8354:\n"
"    BL      sub_FFCF7DC0_my \n"  // --> Patched. Old value = 0xFFCF7DC0.
"    B       loc_FFCF8398 \n"

"loc_FFCF835C:\n"
"    LDR     R1, [R0, #0x10] \n"
"    LDR     R0, [R0, #4] \n"
"    BL      sub_FFDE8D20 \n"
"    B       loc_FFCF8398 \n"

"loc_FFCF836C:\n"
"    LDR     R0, [R4, #0x38] \n"
"    CMP     R0, #5 \n"
"    STRNE   R5, [R4, #0x28] \n"
"    B       loc_FFCF8398 \n"

"loc_FFCF837C:\n"
"    BL      sub_FFCF7BCC \n"
"    B       loc_FFCF8398 \n"

"loc_FFCF8384:\n"
"    BL      sub_FFCF7A90 \n"
"    B       loc_FFCF8398 \n"

"loc_FFCF838C:\n"
"    BL      sub_FFCF78EC \n"
"    B       loc_FFCF8398 \n"

"loc_FFCF8394:\n"
"    BL      sub_FFCF8504 \n"

"loc_FFCF8398:\n"
"    LDR     R1, [SP, #4] \n"
"    MOV     R3, #0x330 \n"
"    STR     R6, [R1] \n"
"    STR     R3, [SP] \n"
"    LDR     R0, [R4, #0x1C] \n"
"    LDR     R3, =0xFFCF774C \n"
"    MOV     R2, R7 \n"
"    BL      sub_FFC1710C /*_PostMessageQueueStrictly*/ \n"
"    B       loc_FFCF82C8 \n"
);
}

/*************************************************************/
//** sub_FFCF7DC0_my @ 0xFFCF7DC0 - 0xFFCF7FC0, length=129
void __attribute__((naked,noinline)) sub_FFCF7DC0_my() {
asm volatile (
"    STMFD   SP!, {R4-R8,LR} \n"
"    SUB     SP, SP, #0x40 \n"
"    MOV     R6, #0 \n"
"    LDR     R5, =0x5648 \n"
"    MOV     R4, R0 \n"
"    STR     R6, [SP, #0x30] \n"
"    STR     R6, [SP, #0x28] \n"
"    LDR     R0, [R5, #0x38] \n"
"    MOV     R8, #4 \n"
"    CMP     R0, #3 \n"
"    STREQ   R8, [R5, #0x38] \n"
"    LDR     R0, [R5, #0xA0] \n"
"    BLX     R0 \n"
"    LDR     R0, [R5, #0x38] \n"
"    CMP     R0, #4 \n"
"    BNE     loc_FFCF7E98 \n"
"    ADD     R3, SP, #0x28 \n"
"    ADD     R2, SP, #0x2C \n"
"    ADD     R1, SP, #0x30 \n"
"    ADD     R0, SP, #0x34 \n"
"    BL      sub_FFDE8EB4 \n"
"    CMP     R0, #0 \n"
"    MOV     R7, #1 \n"
"    BNE     loc_FFCF7E3C \n"
"    LDR     R1, [R5, #0x28] \n"
"    CMP     R1, #1 \n"
"    BNE     loc_FFCF7EA0 \n"
"    LDR     R1, [R5, #0x50] \n"
"    LDR     R2, [R5, #0x3C] \n"
"    CMP     R1, R2 \n"
"    BCC     loc_FFCF7EA0 \n"

"loc_FFCF7E3C:\n"
"    CMP     R0, #0x80000001 \n"
"    STREQ   R8, [R5, #0x54] \n"
"    BEQ     loc_FFCF7E74 \n"
"    CMP     R0, #0x80000003 \n"
"    STREQ   R7, [R5, #0x54] \n"
"    BEQ     loc_FFCF7E74 \n"
"    CMP     R0, #0x80000005 \n"
"    MOVEQ   R0, #2 \n"
"    BEQ     loc_FFCF7E70 \n"
"    CMP     R0, #0x80000007 \n"
"    STRNE   R6, [R5, #0x54] \n"
"    BNE     loc_FFCF7E74 \n"
"    MOV     R0, #3 \n"

"loc_FFCF7E70:\n"
"    STR     R0, [R5, #0x54] \n"

"loc_FFCF7E74:\n"
"    LDR     R0, =0x29500 \n"
"    LDR     R0, [R0, #8] \n"
"    CMP     R0, #0 \n"
"    BEQ     loc_FFCF7E8C \n"
"    BL      sub_FFC32704 \n"
"    B       loc_FFCF7E90 \n"

"loc_FFCF7E8C:\n"
"    BL      sub_FFCF78EC \n"

"loc_FFCF7E90:\n"
"    MOV     R0, #5 \n"
"    STR     R0, [R5, #0x38] \n"

"loc_FFCF7E98:\n"
"    ADD     SP, SP, #0x40 \n"
"    LDMFD   SP!, {R4-R8,PC} \n"

"loc_FFCF7EA0:\n"
"    LDR     LR, [SP, #0x30] \n"
"    CMP     LR, #0 \n"
"    BEQ     loc_FFCF7F68 \n"
"    STR     R7, [R5, #0x2C] \n"
"    LDR     R0, [R5, #0x6C] \n"
"    LDR     R1, [R4, #0x14] \n"
"    LDR     R2, [R4, #0x18] \n"
"    LDR     R12, [R4, #0xC] \n"
"    ADD     R3, SP, #0x38 \n"
"    ADD     R8, SP, #0x14 \n"
"    STMIA   R8, {R0-R3} \n"
"    LDR     R3, [R5, #0x58] \n"
"    ADD     R2, SP, #0x3C \n"
"    ADD     R8, SP, #8 \n"
"    LDRD    R0, [SP, #0x28] \n"
"    STMIA   R8, {R0,R2,R3} \n"
"    STR     R1, [SP, #4] \n"
"    STR     LR, [SP] \n"
"    LDMIB   R4, {R0,R1} \n"
"    LDR     R3, [SP, #0x34] \n"
"    MOV     R2, R12 \n"
"    BL      sub_FFDB912C \n"
"    LDR     R0, [R5, #0x10] \n"
"    MOV     R1, #0x3E8 \n"
"    BL      _TakeSemaphore \n"
"    CMP     R0, #9 \n"
"    BNE     loc_FFCF7F1C \n"
"    BL      sub_FFDE9490 \n"
"    MOV     R0, #0x90000 \n"
"    STR     R7, [R5, #0x38] \n"
"    B       loc_FFCF7F34 \n"

"loc_FFCF7F1C:\n"
"    LDR     R0, [SP, #0x38] \n"
"    CMP     R0, #0 \n"
"    BEQ     loc_FFCF7F3C \n"
"    BL      sub_FFDE9490 \n"
"    MOV     R0, #0xA0000 \n"
"    STR     R7, [R5, #0x38] \n"

"loc_FFCF7F34:\n"
"    BL      sub_FFC5DE6C /*_HardwareDefect_FW*/ \n"
"    B       loc_FFCF7E98 \n"

"loc_FFCF7F3C:\n"
"    BL      sub_FFDB91F0 \n"
"    LDR     R0, [SP, #0x34] \n"
"    LDR     R1, [SP, #0x3C] \n"
"    BL      sub_FFDE9238 \n"
"    LDR     R0, [R5, #0x4C] \n"
"    LDR     R1, =0x56B4 \n"
"    ADD     R0, R0, #1 \n"
"    STR     R0, [R5, #0x4C] \n"
"    LDR     R0, [SP, #0x3C] \n"
"    MOV     R2, #0 \n"
"    BL      sub_FFDE70B0_my \n"  // --> Patched. Old value = 0xFFDE70B0.

"loc_FFCF7F68:\n"
"    LDR     R0, [R5, #0x50] \n"
"    ADD     R0, R0, #1 \n"
"    STR     R0, [R5, #0x50] \n"
"    LDR     R1, [R5, #0x78] \n"
"    MUL     R0, R1, R0 \n"
"    LDR     R1, [R5, #0x74] \n"
"    BL      sub_FFE62B00 \n"
"    MOV     R4, R0 \n"
"    BL      sub_FFDE94C8 \n"
"    LDR     R1, [R5, #0x70] \n"
"    CMP     R1, R4 \n"
"    BNE     loc_FFCF7FA4 \n"
"    LDR     R0, [R5, #0x30] \n"
"    CMP     R0, #1 \n"
"    BNE     loc_FFCF7FB8 \n"

"loc_FFCF7FA4:\n"
"    LDR     R1, [R5, #0x84] \n"
"    MOV     R0, R4 \n"
"    BLX     R1 \n"
"    STR     R4, [R5, #0x70] \n"
"    STR     R6, [R5, #0x30] \n"

"loc_FFCF7FB8:\n"
"    STR     R6, [R5, #0x2C] \n"
"    B       loc_FFCF7E98 \n"
"    BX      LR \n"
);
}

/*************************************************************/
//** sub_FFDE70B0_my @ 0xFFDE70B0 - 0xFFDE7190, length=57
void __attribute__((naked,noinline)) sub_FFDE70B0_my() {
asm volatile (
"    STMFD   SP!, {R4-R8,LR} \n"
"    LDR     R4, =0x89FC \n"
"    LDR     LR, [R4] \n"
"    LDR     R2, [R4, #8] \n"
"    CMP     LR, #0 \n"
"    LDRNE   R3, [R4, #0xC] \n"
"    MOV     R5, R2 \n"
"    CMPNE   R3, #1 \n"
"    MOVEQ   R2, #0 \n"
"    STREQ   R0, [R4] \n"
"    STREQ   R2, [R4, #0xC] \n"
"    BEQ     loc_FFDE717C \n"
"    LDR     R3, [R4, #4] \n"
//"  LDR     R7, =0xFFEAED98 \n"
"    LDR     R7, =table\n"
"    ADD     R12, R3, R3, LSL#1 \n"
"    LDR     R3, [R7, R12, LSL#2] \n"
"    ADD     R6, R7, #0x30 \n"
"    LDR     R8, [R6, R12, LSL#2] \n"
"    SUB     R3, LR, R3 \n"
"    CMP     R3, #0 \n"
"    SUB     LR, LR, R8 \n"
"    BLE     loc_FFDE7138 \n"
"    ADD     R12, R7, R12, LSL#2 \n"
"    LDR     LR, [R12, #4] \n"
"    CMP     LR, R3 \n"
"    ADDGE   R2, R2, #1 \n"
"    BGE     loc_FFDE712C \n"
"    LDR     R12, [R12, #8] \n"
"    CMP     R12, R3 \n"
"    ADDLT   R2, R2, #3 \n"
"    ADDGE   R2, R2, #2 \n"

"loc_FFDE712C:\n"
"    CMP     R2, #0x1A \n"  // --> Patched. Old value = 0x17.
"    MOVGE   R2, #0x19 \n"  // --> Patched. Old value = 0x16.
"    B       loc_FFDE716C \n"

"loc_FFDE7138:\n"
"    CMP     LR, #0 \n"
"    BGE     loc_FFDE716C \n"
"    ADD     R3, R6, R12, LSL#2 \n"
"    LDR     R12, [R3, #4] \n"
"    CMP     R12, LR \n"
"    SUBLE   R2, R2, #1 \n"
"    BLE     loc_FFDE7164 \n"
"    LDR     R3, [R3, #8] \n"
"    CMP     R3, LR \n"
"    SUBGT   R2, R2, #3 \n"
"    SUBLE   R2, R2, #2 \n"

"loc_FFDE7164:\n"
"    CMP     R2, #0 \n"
"    MOVLT   R2, #0 \n"

"loc_FFDE716C:\n"
"    CMP     R2, R5 \n"
"    STRNE   R2, [R4, #8] \n"
"    MOVNE   R2, #1 \n"
"    STRNE   R2, [R4, #0xC] \n"

"loc_FFDE717C:\n"
//"  LDR     R2, =0xFFEAED3C \n"  // Replaced by next instruction
"    LDR     R2, =CompressionRateTable\n"
"    LDR     R3, [R4, #8] \n"
"    LDR     R2, [R2, R3, LSL#2] \n"

"    LDR     R3, =video_mode\n"         // +
"    LDR     R3, [R3]\n"                // +
"    LDR     R3, [R3]\n"                // +
"    CMP     R3, #1\n"                  // +
"    LDREQ   R3, =video_quality\n"      // +
"    LDREQ   R3, [R3]\n"                // +
"    LDREQ   R2, [R3]\n"                // +

"    STR     R2, [R1] \n"
"    STR     R0, [R4] \n"
"    LDMFD   SP!, {R4-R8,PC} \n"
);
}
