void __attribute__((naked,noinline)) sub_FFC5F214_my(){
asm volatile(
"                 LDR     R12, =0x202E\n"
"                 STMFD   SP!, {R4,LR}\n"
"                 CMP     R0, R12\n"
"                 BEQ     loc_FFC5F2D4\n"
"                 BGT     loc_FFC5F270\n"
"                 LDR     R12, =0x2004\n"
"                 CMP     R0, R12\n"
"                 BEQ     loc_FFC5F2DC\n"
"                 BGT     loc_FFC5F258\n"
"                 SUB     R12, R0, #0x1000\n"
"                 SUBS    R12, R12, #0xA9\n"
"                 SUBNE   R12, R0, #0x1000\n"
"                 SUBNES  R12, R12, #0xAD\n"
"                 SUBNE   R12, R0, #0x1000\n"
"                 SUBNES  R12, R12, #0xAF\n"
"                 BNE     loc_FFC5F2EC\n"
"                 B       loc_FFC5F2D4\n"
" loc_FFC5F258:\n"
"                 SUB     R12, R0, #0x2000\n"
"                 SUBS    R12, R12, #5\n"
"                 SUBNE   R12, R0, #0x2000\n"
"                 SUBNES  R12, R12, #0x1D\n"
"                 BNE     loc_FFC5F2EC\n"
"                 B       loc_FFC5F2D4\n"
" loc_FFC5F270:\n"
"                 LDR     R12, =0x5004\n"
"                 CMP     R0, R12\n"
"                 BEQ     loc_FFC5F2D4\n"
"                 BGT     loc_FFC5F29C\n"
"                 SUB     R12, R0, #0x3000\n"
"                 SUBS    R12, R12, #0xA\n"
"                 BEQ     loc_FFC5F2D0\n"
"                 SUB     R12, R0, #0x5000\n"
"                 SUBS    R12, R12, #1\n"
"                 BNE     loc_FFC5F2EC\n"
"                 B       loc_FFC5F2D4\n"
" loc_FFC5F29C:\n"
"                 SUB     R12, R0, #0x5000\n"
"                 SUBS    R12, R12, #6\n"
"                 BEQ     loc_FFC5F2D4\n"
"                 SUB     R12, R0, #0x5000\n"
"                 SUBS    R12, R12, #7\n"
"                 BNE     loc_FFC5F2EC\n"
"                 BL      sub_FFC19A84\n"
"                 LDR     R1, =0x55E0\n"
"                 LDR     R0, [R1,#0x10]\n"
"                 CMP     R0, #7\n"
"                 LDREQ   R0, [R1,#0x18]\n"
"                 BLEQ    sub_FFC5FCC0\n"
"                 B       loc_FFC5F2E4\n"
" loc_FFC5F2D0:\n"
"                 BL      sub_FFC18EEC\n"
" loc_FFC5F2D4:\n"
"                 LDMFD   SP!, {R4,LR}\n"
"                 B       sub_FFC5F050_my\n"
" loc_FFC5F2DC:\n"
"                 BL      sub_FFC5DEB0\n"
"                 BL      sub_FFC5EA10\n"
" loc_FFC5F2E4:\n"
"                 MOV     R0, #0\n"
"                 LDMFD   SP!, {R4,PC}\n"
" loc_FFC5F2EC:\n"
"                 MOV     R0, #1\n"
"                 LDMFD   SP!, {R4,PC}\n"
	);
}






void __attribute__((naked,noinline)) sub_FFC5F050_my(){
asm volatile(
"                 STMFD   SP!, {R4-R6,LR}\n"
"                 BL      sub_FFC5FDB0\n"
"                 CMP     R0, #1\n"
"                 BLEQ    sub_FFC5EA70\n"
"                 LDR     R4, =0x55E0\n"
"                 MOV     R5, #1\n"
"                 LDR     R0, [R4,#0x24]\n"
"                 CMP     R0, #0\n"
"                 LDRNE   R0, [R4,#0x4C]\n"
"                 CMPNE   R0, #0\n"
"                 BEQ     loc_FFC5F0B4\n"
"                 BL      sub_FFC5FDB0\n"
"                 CMP     R0, #1\n"
"                 BNE     loc_FFC5F0B4\n"
"                 BL      sub_FFC5EA70\n"
"                 LDR     R0, [R4,#0x78]\n"
"                 CMP     R0, #0\n"
"                 BNE     loc_FFC5F0B4\n"
"                 ADR     R1, aAcStartupshowi ; "AC:StartupShowInfo"\n"
"                 MOV     R0, #0x60\n"
"                 BL      sub_FFC5673C\n"
"                 MOV     R1, #0\n"
"                 MOV     R0, #0x53\n"
"                 BL      sub_FFC676C4\n"
"                 STR     R5, [R4,#0x78]\n"
" loc_FFC5F0B4:\n"
"                 BL      sub_FFC5FDB0\n"
"                 CMP     R0, #1\n"
"                 BNE     loc_FFC5F100\n"
"                 LDR     R0, [R4,#0x44]\n"
"                 CMP     R0, #0\n"
"                 BEQ     loc_FFC5F100\n"
"                 LDR     R0, [R4,#0x74]\n"
"                 CMP     R0, #0\n"
"                 BNE     loc_FFC5F100\n"
"                 ADR     R1, aAcDispshot ; "AC:DispShot"\n"
"                 MOV     R0, #0x60\n"
"                 BL      sub_FFC5673C\n"
"                 MOV     R1, #0\n"
"                 MOV     R0, #0x8C\n"
"                 BL      sub_FFC676C4\n"
"                 BL      sub_FFC658E8\n"
"                 MOV     R0, #0x21\n"
"                 BL      sub_FFC67704\n"
"                 STR     R5, [R4,#0x74]\n"
"\n"
" loc_FFC5F100:\n"
"                 LDR     R0, [R4,#0x38]\n"
"                 CMP     R0, #0\n"
"                 LDRNE   R0, [R4,#0x3C]\n"
"                 CMPNE   R0, #0\n"
"                 LDRNE   R0, [R4,#0x44]\n"
"                 CMPNE   R0, #0\n"
"                 LDRNE   R0, [R4,#0x48]\n"
"                 CMPNE   R0, #0\n"
"                 LDRNE   R0, [R4,#0x1C]\n"
"                 LDRNE   R1, [R4,#0x20]\n"
"                 ORRNES  R0, R0, R1\n"
"                 BEQ     loc_FFC5F140\n"
"                 BL      sub_FFC5E7BC\n"
"                 BL      sub_FFC19018\n"
"                 BL      sub_FFC5EA10\n"
"                 B       loc_FFC5F168\n"
" loc_FFC5F140:\n"
"                 LDR     R0, [R4,#0x58]\n"
"                 CMP     R0, #0\n"
"                 BEQ     loc_FFC5F1E4\n"
"                 BL      sub_FFC5E8AC\n"
"                 CMP     R0, #1\n"
"                 BNE     loc_FFC5F1E4\n"
"                 BL      sub_FFC6143C\n"
"                 BL      sub_FFC613F8\n"
"                 MOV     R0, #0\n"
"                 BL      sub_FFC5FCFC\n"
" loc_FFC5F168:\n"
"                 MOV     R0, #0\n"
"                 LDMFD   SP!, {R4-R6,PC}\n"
" loc_FFC5F1E4:\n"
"                 BL      sub_FFC5E8AC\n"
"                 CMP     R0, #1\n"
"                 BNE     loc_FFC5F20C\n"
"                 LDR     R0, [R4,#0x7C]\n"
"                 CMP     R0, #0\n"
"                 BLEQ    sub_FFC5FE3C_my\n"
"                 MOV     R0, #0\n"
"                 STR     R0, [R4,#0x70]\n"
"                 STR     R0, [R4,#0x74]\n"
"                 STR     R0, [R4,#0x78]\n"
" loc_FFC5F20C:\n"
"                 MOV     R0, #1\n"
"                 LDMFD   SP!, {R4-R6,PC}\n"
);
}






void __attribute__((naked,noinline)) sub_FFC5FE3C_my(){ 
 asm volatile(
"                 STMFD   SP!, {R4,LR}\n"
"                 ADR     R1, aAcEntryrecboot ; "AC:EntryRecBoot"\n"
"                 MOV     R0, #0x60\n"
"                 BL      sub_FFC5673C\n"
"                 BL      sub_FFC19150\n"
"                 BL      sub_FFC600E0\n"
"                 BL      sub_FFC63624_my\n"
"                 MOV     R0, #1\n"
"                 BL      sub_FFC5E250\n"
"                 BL      sub_FFC5E740\n"
"                 LDMFD   SP!, {R4,LR}\n"
"                 B       sub_FFC5EAB8\n"
 );
} 





void __attribute__((naked,noinline)) sub_FFC63624_my(){ 
 asm volatile(
"                 STMFD   SP!, {R4-R6,LR}\n"
"                 ADR     R1, aStartrecmode ; "StartRecMode"\n"
"                 MOV     R0, #0x60\n"
"                 BL      sub_FFC5673C\n"
"                 LDR     R4, =0x588C\n"
"                 MOV     R0, #6\n"
"                 MOV     R5, #1\n"
"                 STR     R0, [R4,#0x5C]\n"
"                 STR     R5, [R4,#0x10]\n"
"                 BL      sub_FFD2DFB4\n"
"                 BL      sub_FFD34228\n"
"                 BL      sub_FFD32A0C\n"
"                 BL      sub_FFC63AAC_my\n"
"                 BL      sub_FFD3C1A0\n"
"                 MOV     R0, #1\n"
"                 STR     R5, [R4,#0x18]\n"
"                 BL      sub_FFC63B64\n"
"                 MOV     R0, #3\n"
"                 STR     R0, [R4,#0x60]\n"
"                 LDR     R1, [R4,#0x64]\n"
"                 LDMFD   SP!, {R4-R6,LR}\n"
"                 MOV     R0, #0\n"
"                 BX      R1\n"
 );
} 





void __attribute__((naked,noinline)) sub_FFC63AAC_my(){ 
 asm volatile(
"                 STMFD   SP!, {R4,LR}\n"
"                 LDR     R0, =0x85E\n"
"                 BL      sub_FFD2A374\n"
"                 BL      sub_FFC18EEC\n"
"                 BL      sub_FFC633DC_my\n"
"                 BL      sub_FFD2D7D4\n"
"                 BL      sub_FFD1AE64\n"
"                 BL      sub_FFD35AE4\n"
"                 BL      sub_FFD360CC\n"
"                 BL      sub_FFD3BCC8\n"
"                 BL      sub_FFD362F4\n"
"                 BL      sub_FFD35EBC\n"
"                 BL      sub_FFD3BDD0\n"
"                 BL      sub_FFD34A9C\n"
"                 BL      sub_FFD3B920\n"
"                 BL      sub_FFC677A4\n"
"                 LDMFD   SP!, {R4,LR}\n"
"                 B       sub_FFC67598\n"
 );
} 




// branches are together

void __attribute__((naked,noinline)) sub_FFC633DC_my(){ 
 asm volatile(
"                 STMFD   SP!, {R4,LR}\n"
"                 LDR     R0, =0x58F4\n"
"                 ADR     R1, sub_FFC631DC_my\n"
"                 BL      sub_FFC68368\n"
"                 LDR     R1, =0x588C\n"
"                 ADR     R0, sub_FFC63304_my\n"
"                 STR     R0, [R1,#0x64]\n"
"                 LDMFD   SP!, {R4,PC}\n"
 );
} 



//branch 1

void __attribute__((naked,noinline)) sub_FFC631DC_my(){ 
 asm volatile(
"                 STMFD   SP!, {R3-R5,LR}\n"
"                 LDR     R4, =0x588C\n"
"                 LDR     R0, [R4,#0x3C]\n"
"                 CMP     R0, #0\n"
"                 BLEQ    sub_FFD19AC8\n"
"                 LDR     R0, [R4,#0x30]\n"
"                 CMP     R0, #1\n"
"                 BNE     loc_FFC6321C\n"
"                 ADR     R1, a__preparecaptu ; "__PrepareCaptureModeChange__"\n"
"                 MOV     R0, #0x60\n"
"                 BL      sub_FFC5673C\n"
"                 MOV     R0, #0\n"
"                 STR     R0, [R4,#0x30]\n"
"                 STR     R0, [R4,#0x2C]\n"
"                 BL      sub_FFC630D4\n"
"                 LDMFD   SP!, {R3-R5,PC}\n"
" loc_FFC6321C:\n"
"                 BL      sub_FFC14B24\n"
"                 LDRH    R0, [R4,#4]\n"
"                 MOV     R1, SP\n"
"                 STRH    R0, [SP,#0x10+var_10]\n"
"                 LDR     R0, [R4,#0x5C]\n"
"                 STRH    R0, [SP,#0x10+var_E]\n"
"                 MOV     R0, #0x40\n"
"                 BL      sub_FFC676C4\n"
"                 LDR     R0, [R4,#0x1C]\n"
"                 CMP     R0, #0\n"
"                 LDREQH  R0, [R4,#4]\n"
"                 BLEQ    sub_FFC5D5F4\n"
"                 LDRH    R0, [R4,#4]\n"
"                 MOV     R1, #1\n"
"                 BL      sub_FFC62410_my\n"
"                 LDR     R0, [R4,#0x60]\n"
"                 BL      sub_FFC63B64\n"
"                 MOV     R0, #3\n"
"                 STR     R0, [R4,#0x60]\n"
"                 LDR     R1, [R4,#0x64]\n"
"                 ADD     SP, SP, #4\n"
"                 LDMFD   SP!, {R4,R5,LR}\n"
"                 MOV     R0, #0\n"
"                 BX      R1\n"

 );
} 




//branch 2

void __attribute__((naked,noinline)) sub_FFC63304_my(){ 
 asm volatile(
"                 STMFD   SP!, {R4-R6,LR}\n"
"                 LDR     R4, =0x588C\n"
"                 LDRH    R0, [R4,#4]\n"
"                 BL      sub_FFD34460\n"
"                 BL      sub_FFD32C7C\n"
"                 BL      sub_FFD36374\n"
//"                 BL      nullsub_532\n"
"                 BL      sub_FFD34C20\n"
"                 BL      sub_FFD1CAA4\n"
"                 MOV     R5, #0\n"
"                 MOV     R0, R5\n"
"                 STR     R5, [R4,#0x24]\n"
"                 BL      sub_FFC14B50\n"
"                 BL      sub_FFD1C17C\n"
"                 STR     R5, [R4,#0x3C]\n"
"                 LDRH    R0, [R4,#4]\n"
"                 MOV     R1, #0\n"
"                 BL      sub_FFC62410_my\n"
"                 BL      sub_FFC658E8\n"
"                 LDR     R1, [R4,#0x5C]\n"
"                 MOV     R0, #0x41\n"
"                 BL      sub_FFC676C4\n"
"                 BL      sub_FFD32C6C\n"
"                 BL      sub_FFD2E128\n"
"                 CMP     R0, #0\n"
"                 BLEQ    sub_FFD32C8C\n"
"                 BL      sub_FFD343E8\n"
"                 BL      sub_FFD19980\n"
"                 BL      sub_FFC5B9EC\n"
"                 STR     R0, [R4,#0x58]\n"
"                 LDR     R0, =0x8003\n"
"                 STR     R5, [R4,#0x2C]\n"
"                 BL      sub_FFC5D6B4\n"
"                 STRH    R0, [R4]\n"
"                 LDR     R0, =0x313D\n"
"                 MOV     R1, #0\n"
"                 BL      PostLogicalEventToUI\n"
"                 BL      sub_FFC63A44\n"
"                 LDR     R0, [R4,#0x30]\n"
"                 CMP     R0, #1\n"
"                 STREQ   R5, [R4,#0x30]\n"
"                 LDMEQFD SP!, {R4-R6,LR}\n"
"                 BEQ     sub_FFC630D4\n"
"                 LDMFD   SP!, {R4-R6,PC}\n"
 );
} 




//branches are joining here

void __attribute__((naked,noinline)) sub_FFC62410_my(){ 
 asm volatile(
"                 STMFD   SP!, {R4-R6,LR}\n"
"                 MOV     R5, R1\n"
"                 MOV     R4, R0\n"
"                 MOV     R0, #0x60\n"
"                 ADR     R1, a_decidecapture ; "_DecideCaptureMode"\n"
"                 BL      sub_FFC5673C\n"
"                 LDR     R6, =0x588C\n"
"                 LDR     R0, [R6,#0x10]\n"
"                 CMP     R0, #0\n"
"                 BEQ     loc_FFC6253C\n"
"                 LDR     R0, [R6,#0x18]\n"
"                 LDR     R2, =0x820A\n"
"                 LDR     R1, =unk_FFFE0000\n"
"                 CMP     R0, #1\n"
"                 BNE     loc_FFC62484\n"
"                 CMP     R5, #1\n"
"                 LDMEQFD SP!, {R4-R6,PC}\n"
"                 CMP     R5, #0\n"
"                 BNE     loc_FFC62484\n"
"                 CMP     R4, R2\n"
"                 BEQ     loc_FFC6247C\n"
"                 CMP     R1, R4,LSL#17\n"
"                 TSTNE   R4, #0xC00\n"
"                 BEQ     loc_FFC62478\n"
"                 BL      sub_FFC63908_my\n"
"                 B       loc_FFC6247C\n"
" loc_FFC62478:\n"
"                 BL      sub_FFC638BC\n"
" loc_FFC6247C:\n"
"                 BL      sub_FFC63AA8\n"
"                 B       loc_FFC6253C\n"
" loc_FFC62484:\n"
"                 CMP     R4, R2\n"
"                 BEQ     loc_FFC62534\n"
"                 CMP     R1, R4,LSL#17\n"
"                 LDRH    R0, [R6,#2]\n"
"                 TSTNE   R4, #0xC00\n"
"                 BEQ     loc_FFC624E4\n"
"                 CMP     R0, R2\n"
"                 BEQ     loc_FFC62534\n"
"                 CMP     R1, R0,LSL#17\n"
"                 TSTNE   R0, #0xC00\n"
"                 BEQ     loc_FFC624C8\n"
"                 ADR     R1, a_movietomovie ; "_MovieToMovie"\n"
"                 MOV     R0, #0x60\n"
"                 BL      sub_FFC5673C\n"
"                 CMP     R5, #1\n"
"                 BEQ     loc_FFC6250C\n"
"                 B       loc_FFC624DC\n"
" loc_FFC624C8:\n"
"                 ADR     R1, a_stilltomovie ; "_StillToMovie"\n"
"                 MOV     R0, #0x60\n"
"                 BL      sub_FFC5673C\n"
"                 CMP     R5, #1\n"
"                 BEQ     loc_FFC62528\n"
" loc_FFC624DC:\n"
"                 BL      sub_FFC63908_my\n"
"                 B       loc_FFC62534\n"
" loc_FFC624E4:\n"
"                 CMP     R0, R2\n"
"                 BEQ     loc_FFC62534\n"
"                 CMP     R1, R0,LSL#17\n"
"                 TSTNE   R0, #0xC00\n"
"                 BEQ     loc_FFC62514\n"
"                 ADR     R1, a_movietostill ; "_MovieToStill"\n"
"                 MOV     R0, #0x60\n"
"                 BL      sub_FFC5673C\n"
"                 CMP     R5, #1\n"
"                 BNE     loc_FFC62530\n"
" loc_FFC6250C:\n"
"                 LDMFD   SP!, {R4-R6,LR}\n"
"                 B       sub_FFC63934\n"
" loc_FFC62514:\n"
"                 ADR     R1, a_stilltostill ; "_StillToStill"\n"
"                 MOV     R0, #0x60\n"
"                 BL      sub_FFC5673C\n"
"                 CMP     R5, #1\n"
"                 BNE     loc_FFC62530\n"
" loc_FFC62528:\n"
"                 LDMFD   SP!, {R4-R6,LR}\n"
"                 B       sub_FFC638E4\n"
" loc_FFC62530:\n"
"                 BL      sub_FFC638BC\n"
" loc_FFC62534:\n"
"                 CMP     R5, #0\n"
"                 LDMNEFD SP!, {R4-R6,PC}\n"
" loc_FFC6253C:\n"
"                 STRH    R4, [R6,#2]\n"
"                 LDMFD   SP!, {R4-R6,PC}\n"

 );
} 

void __attribute__((naked,noinline)) sub_FFC63908_my(){ 
 asm volatile(
"                 STMFD   SP!, {R4,LR}\n"
"                 ADR     R1, a_startmovie ; "_StartMovie"\n"
"                 MOV     R0, #0x60\n"
"                 BL      sub_FFC5673C\n"
"                 LDR     R0, =0x588C\n"
"                 LDR     R0, [R0,#0x28]\n"
"                 CMP     R0, #0\n"
"                 BLNE    sub_FFC643F0\n"
"                 LDMFD   SP!, {R4,LR}\n"
"                 MOV     R0, #0\n"
"                 B       sub_FFC66824_my\n"
 );
} 






void __attribute__((naked,noinline)) sub_FFC66824_my(){ 
 asm volatile(
"                 STMFD   SP!, {R4,LR}\n"
"                 LDR     R4, =0x5A40\n"
"                 MOV     R0, #0\n"
"                 STR     R0, [R4,#0x30]\n"
"                 LDR     R0, [R4,#8]\n"
"                 CMP     R0, #0\n"
"                 BNE     loc_FFC66850\n"
"                 MOV     R1, #0\n"
"                 ADR     R0, sub_FFC6642C_my\n"
"                 BL      sub_FFC5BC6C\n"
"                 STR     R0, [R4,#8]\n"
" loc_FFC66850:\n"
"                 LDR     R0, [R4,#0xC]\n"
"                 CMP     R0, #0\n"
"                 BNE     loc_FFC6686C\n"
"                 LDR     R0, =sub_FFC660CC\n"
"                 MOV     R1, #0\n"
"                 BL      sub_FFC63540\n"
"                 STR     R0, [R4,#0xC]\n"
" loc_FFC6686C:\n"
"                 BL      sub_FFC66FC4\n"
"                 BL      sub_FFC66130\n"
"                 BL      sub_FFC67B14\n"
"                 BL      sub_FFD3CB0C\n"
"                 LDMFD   SP!, {R4,LR}\n"
"                 B       sub_FFD33A30\n"

 );
} 

void __attribute__((naked,noinline)) sub_FFC6642C_my(){ 
 asm volatile(
"                 STMFD   SP!, {R3-R11,LR}\n"
"                 LDR     R5, =0x5A40\n"
"                 MOV     R4, R1\n"
"                 LDR     R2, [R5,#0x2C]\n"
"                 ADD     R0, R5, #0\n"
"                 LDR     R0, [R0,#0x14]\n"
"                 LDR     R9, =0x3007\n"
"                 CMP     R2, #0\n"
"                 MOV     R1, #0\n"
"                 MOV     R11, R3\n"
"                 MOVL    R8, 0xFFFFFFFF\n"
"                 BEQ     loc_FFC664A4\n"
"                 CMP     R4, R9\n"
"                 BEQ     loc_FFC66698\n"
"                 CMP     R4, #0x800\n"
"                 LDREQ   R2, [R5,#0x38]\n"
"                 CMPEQ   R11, R2\n"
"                 BNE     loc_FFC667A8\n"
"                 STR     R1, [R5,#0x2C]!\n"
"                 CMP     R0, #0\n"
"                 STR     R8, [R5,#0xC]\n"
"                 BNE     loc_FFC6681C\n"
"                 BL      sub_FFC199C4\n"
"                 CMP     R0, #1\n"
"                 BEQ     loc_FFC6649C\n"
"                 BL      sub_FFC199CC\n"
"                 CMP     R0, #1\n"
"                 BNE     loc_FFC6681C\n"
" loc_FFC6649C:\n"
"                 BL      sub_FFC6627C\n"
"                 B       loc_FFC6681C\n"
" loc_FFC664A4:\n"
"                 CMP     R0, #1\n"
"                 SUBEQ   R12, R4, #0x2000\n"
"                 SUBEQS  R12, R12, #0x1C\n"
"                 BNE     loc_FFC664C0\n"
"                 MOV     R0, #0\n"
"                 BL      sub_FFC66B24\n"
"                 B       loc_FFC6681C\n"
" loc_FFC664C0:\n"
"                 BL      sub_FFD239EC\n"
"                 LDR     R10, =0x9A5\n"
"                 CMP     R0, #1\n"
"                 SUB     R6, R10, #4\n"
"                 SUB     R7, R10, #2\n"
"                 BNE     loc_FFC664F4\n"
"                 CMP     R4, R10\n"
"                 CMPNE   R4, R6\n"
"                 CMPNE   R4, R7\n"
"                 BNE     loc_FFC664F4\n"
"                 BL      sub_FFD22B80\n"
"                 STR     R4, [R5,#0x3C]\n"
"                 B       loc_FFC667A8\n"
" loc_FFC664F4:\n"
"                 BL      sub_FFD32AC4\n"
"                 CMP     R0, #1\n"
"                 BNE     loc_FFC66514\n"
"                 MOV     R0, R4\n"
"                 BL      sub_FFC5C198\n"
"                 CMP     R0, #1\n"
"                 CMPNE   R4, R10\n"
"                 BEQ     loc_FFC667A8\n"
" loc_FFC66514:\n"
"                 BL      sub_FFC19AB4\n"
"                 CMP     R0, #1\n"
"                 BNE     loc_FFC6652C\n"
"                 CMP     R4, R6\n"
"                 CMPNE   R4, R7\n"
"                 BEQ     loc_FFC6681C\n"
" loc_FFC6652C:\n"
"                 BL      sub_FFC631D0\n"
"                 LDR     R1, =0x9A2\n"
"                 CMP     R0, #1\n"
"                 ADD     R2, R1, #2\n"
"                 BNE     loc_FFC66554\n"
"                 CMP     R4, R6\n"
"                 CMPNE   R4, R1\n"
"                 CMPNE   R4, R7\n"
"                 CMPNE   R4, R2\n"
"                 BEQ     loc_FFC6681C\n"
" loc_FFC66554:\n"
"                 LDR     R12, =0x200A\n"
"                 CMP     R4, R12\n"
"                 BEQ     loc_FFC6680C\n"
"                 BGT     loc_FFC665D4\n"
"                 LDR     R12, =0x907\n"
"                 CMP     R4, R12\n"
"                 MOVEQ   R1, #2\n"
"                 MOVEQ   R0, R10\n"
"                 BEQ     loc_FFC66748\n"
"                 BGT     loc_FFC665B0\n"
"                 SUB     R12, R4, #0x800\n"
"                 LDR     R6, =0x2003\n"
"                 SUBS    R12, R12, #0x2A\n"
"                 BEQ     loc_FFC666AC\n"
"                 SUB     R12, R4, #0x800\n"
"                 SUBS    R12, R12, #0x2E\n"
"                 BEQ     loc_FFC666F0\n"
"                 SUB     R12, R4, #0x800\n"
"                 SUBS    R12, R12, #0x6C\n"
"                 SUBNE   R12, R4, #0x800\n"
"                 SUBNES  R12, R12, #0x6D\n"
"                 BNE     loc_FFC667C0\n"
"                 B       loc_FFC667A8\n"
" loc_FFC665B0:\n"
"                 CMP     R4, R6\n"
"                 BEQ     loc_FFC66740\n"
"                 CMP     R4, R1\n"
"                 BEQ     loc_FFC6680C\n"
"                 CMP     R4, R7\n"
"                 BEQ     loc_FFC66740\n"
"                 CMP     R4, R2\n"
"                 BEQ     loc_FFC6680C\n"
"                 B       loc_FFC667C0\n"
" loc_FFC665D4:\n"
"                 LDR     R12, =0x3149\n"
"                 CMP     R4, R12\n"
"                 MOVEQ   R1, #0\n"
"                 MOVEQ   R0, #0x84\n"
"                 BEQ     loc_FFC667B8\n"
"                 BGT     loc_FFC6662C\n"
"                 SUB     R12, R4, #0x2000\n"
"                 SUBS    R12, R12, #0x20\n"
"                 MOVEQ   R1, R11\n"
"                 MOVEQ   R0, #0x83\n"
"                 BEQ     loc_FFC667B8\n"
"                 CMP     R4, R9\n"
"                 BEQ     loc_FFC66684\n"
"                 SUB     R12, R4, #0x3100\n"
"                 SUBS    R12, R12, #0x35\n"
"                 BEQ     loc_FFC66668\n"
"                 SUB     R12, R4, #0x3000\n"
"                 SUBS    R12, R12, #0x148\n"
"                 BNE     loc_FFC667C0\n"
"                 MOV     R1, #0\n"
"                 MOV     R0, #0x86\n"
"                 B       loc_FFC667B8\n"
" loc_FFC6662C:\n"
"                 SUB     R12, R4, #0x3100\n"
"                 SUBS    R12, R12, #0x4A\n"
"                 BEQ     loc_FFC667B0\n"
"                 SUB     R12, R4, #0x4000\n"
"                 SUBS    R12, R12, #3\n"
"                 BEQ     loc_FFC6676C\n"
"                 SUB     R12, R4, #0x4000\n"
"                 SUBS    R12, R12, #8\n"
"                 BEQ     loc_FFC66750\n"
"                 SUB     R12, R4, #0x4000\n"
"                 SUBS    R12, R12, #0xF\n"
"                 BNE     loc_FFC667C0\n"
"                 MOV     R0, #0x82\n"
"                 BL      sub_FFC67704\n"
"                 B       loc_FFC6681C\n"
" loc_FFC66668:\n"
"                 BL      sub_FFC66FF8\n"
"                 CMP     R0, #4\n"
"                 BEQ     loc_FFC6680C\n"
"                 LDR     R0, [R5,#0x1C]\n"
"                 CMP     R0, #0\n"
"                 BLNE    sub_FFC661C4\n"
"                 B       loc_FFC6681C\n"
" loc_FFC66684:\n"
"                 MOV     R0, #1\n"
"                 STR     R0, [R5,#0x1C]\n"
"                 LDR     R0, [R5,#0x18]\n"
"                 CMP     R0, #1\n"
"                 BNE     loc_FFC666A0\n"
" loc_FFC66698:\n"
"                 BL      sub_FFC661C4\n"
"                 LDMFD   SP!, {R3-R11,PC}\n"
" loc_FFC666A0:\n"
"                 MOV     R0, R4\n"
"                 BL      sub_FFC6639C\n"
"                 B       loc_FFC6681C\n"
" loc_FFC666AC:\n"
"                 BL      sub_FFC631D0\n"
"                 CMP     R0, #0\n"
"                 BEQ     loc_FFC666C4\n"
"                 MOV     R0, R4\n"
"                 BL      sub_FFC63730\n"
"                 B       loc_FFC6681C\n"
" loc_FFC666C4:\n"
"                 LDR     R0, [R5,#0x10]\n"
"                 LDR     R1, [R5,#0x14]\n"
"                 ORR     R0, R0, R1\n"
"                 LDR     R1, [R5,#0x1C]\n"
"                 ORRS    R0, R0, R1\n"
"                 BNE     loc_FFC6681C\n"
"                 MOV     R1, #0\n"
"                 MOV     R0, R6\n"
"                 BL      sub_FFC48C7C\n"
"                 BL      sub_FFC59FB4\n"
"                 B       loc_FFC6681C\n"
" loc_FFC666F0:\n"
"                 LDR     R0, [R5,#0x10]\n"
"                 LDR     R1, [R5,#0x14]\n"
"                 ORRS    R0, R0, R1\n"
"                 BNE     loc_FFC6681C\n"
"                 BL      sub_FFC6373C\n"
"                 CMP     R0, #0\n"
"                 LDREQ   R0, [R5,#0x1C]\n"
"                 CMPEQ   R0, #0\n"
"                 BNE     loc_FFC6681C\n"
"                 BL      sub_FFC631D0\n"
"                 CMP     R0, #0\n"
"                 BNE     loc_FFC6681C\n"
"                 BL      sub_FFD3C3DC\n"
"                 CMP     R0, #0\n"
"                 BNE     loc_FFC6681C\n"
"                 MOV     R1, #0\n"
"                 MOV     R0, R6\n"
"                 BL      sub_FFC48C7C\n"
"                 BL      sub_FFD1A82C\n"
"                 B       loc_FFC6681C\n"
" loc_FFC66740:\n"
"                 MOV     R1, #1\n"
"                 MOV     R0, R4\n"
" loc_FFC66748:\n"
"                 BL      sub_FFC662D8_my\n"
"                 LDMFD   SP!, {R3-R11,PC}\n"
" loc_FFC66750:\n"
"                 MOV     R0, R11\n"
"                 BL      sub_FFC61DBC\n"
"                 CMP     R0, #0\n"
"                 MOVEQ   R1, R11\n"
"                 MOVEQ   R0, R4\n"
"                 BLEQ    sub_FFC66CE4_my\n"
"                 B       loc_FFC667A8\n"
" loc_FFC6676C:\n"
"                 LDR     R0, [R5,#0x3C]\n"
"                 CMN     R0, #1\n"
"                 BEQ     loc_FFC667A8\n"
"                 MOV     R0, #0\n"
"                 BL      sub_FFC5A558\n"
"                 LDR     R0, [R5,#0x3C]\n"
"                 CMP     R0, R6\n"
"                 BNE     loc_FFC66798\n"
"                 BL      sub_FFC199C4\n"
"                 CMP     R0, #0\n"
"                 BEQ     loc_FFC667A4\n"
" loc_FFC66798:\n"
"                 LDR     R0, [R5,#0x3C]\n"
"                 MOV     R1, #0\n"
"                 BL      PostLogicalEventForNotPowerType\n"
" loc_FFC667A4:\n"
"                 STR     R8, [R5,#0x3C]\n"
" loc_FFC667A8:\n"
"                 MOV     R0, #1\n"
"                 LDMFD   SP!, {R3-R11,PC}\n"
" loc_FFC667B0:\n"
"                 MOV     R1, #0\n"
"                 MOV     R0, #0x85\n"
" loc_FFC667B8:\n"
"                 BL      sub_FFC676C4\n"
"                 B       loc_FFC6681C\n"
" loc_FFC667C0:\n"
"                 LDR     R12, =0x85E\n"
"                 CMP     R4, R12\n"
"                 BEQ     loc_FFC667FC\n"
"                 BGT     loc_FFC667E8\n"
"                 SUB     R12, R4, #0x800\n"
"                 SUBS    R12, R12, #0x3E\n"
"                 SUBNE   R12, R4, #0x800\n"
"                 SUBNES  R12, R12, #0x3F\n"
"                 BNE     loc_FFC6680C\n"
"                 B       loc_FFC667FC\n"
" loc_FFC667E8:\n"
"                 SUB     R12, R4, #0x800\n"
"                 SUBS    R12, R12, #0x5F\n"
"                 SUBNE   R12, R4, #0x800\n"
"                 SUBNES  R12, R12, #0x68\n"
"                 BNE     loc_FFC6680C\n"
" loc_FFC667FC:\n"
"                 LDR     R0, [R5,#0x10]\n"
"                 LDR     R1, [R5,#0x14]\n"
"                 ORRS    R0, R0, R1\n"
"                 BNE     loc_FFC6681C\n"
" loc_FFC6680C:\n"
"                 MOV     R1, R11\n"
"                 MOV     R0, R4\n"
"                 BL      sub_FFC66CE4_my\n"
"                 LDMFD   SP!, {R3-R11,PC}\n"
" loc_FFC6681C:\n"
"                 MOV     R0, #0\n"
"                 LDMFD   SP!, {R3-R11,PC}\n"

 );
} 

void __attribute__((naked,noinline)) sub_FFC662D8_my(){
asm volatile(
"                 STMFD   SP!, {R4-R6,LR}\n"
"                 MOV     R4, R0\n"
"                 LDR     R0, =0x5A40\n"
"                 MOV     R5, R1\n"
"                 LDR     R0, [R0,#0x1C]\n"
"                 CMP     R0, #0\n"
"                 ADRNE   R1, aMvicon_fshtdwn ; "MviCon_fShtDwn"\n"
"                 BNE     loc_FFC66384\n"
"                 BL      sub_FFC67004\n"
"                 CMP     R0, #1\n"
"                 BNE     loc_FFC66314\n"
" loc_FFC66304:\n"
"                 MOV     R0, R4\n"
"                 LDMFD   SP!, {R4-R6,LR}\n"
"                 MOV     R1, #0\n"
"                 B       sub_FFC66CE4_my\n"
" loc_FFC66314:\n"
"                 CMP     R5, #2\n"
"                 BNE     loc_FFC6632C\n"
"                 BL      sub_FFC658E8\n"
"                 CMP     R0, #0\n"
"                 BEQ     loc_FFC66374\n"
"                 B       loc_FFC66340\n"
" loc_FFC6632C:\n"
"                 CMP     R5, #1\n"
"                 BNE     loc_FFC66374\n"
"                 BL      sub_FFC6596C\n"
"                 CMP     R0, #0\n"
"                 BNE     loc_FFC66374\n"
" loc_FFC66340:\n"
"                 MOV     R0, #0\n"
"                 BL      sub_FFC5A558\n"
"                 SUB     R12, R4, #0x900\n"
"                 SUBS    R12, R12, #0xA1\n"
"                 SUBNE   R12, R4, #0x900\n"
"                 SUBNES  R12, R12, #0xA3\n"
"                 SUBNE   R12, R4, #0x900\n"
"                 SUBNES  R12, R12, #0xA5\n"
"                 LDREQ   R0, =0xC507\n"
"                 MOVEQ   R1, #0\n"
"                 BLEQ    sub_FFC48C7C\n"
" loc_FFC6636C:\n"
"                 MOV     R0, #0\n"
"                 LDMFD   SP!, {R4-R6,PC}\n"
" loc_FFC66374:\n"
"                 BL      sub_FFC6627C\n"
"                 CMP     R0, #0\n"
"                 BNE     loc_FFC66390\n"
"                 ADR     R1, aMvicon_initchk ; "MviCon_InitChkBuf"\n"
" loc_FFC66384:\n"
"                 MOV     R0, #0x60\n"
"                 BL      sub_FFC5673C\n"
"                 B       loc_FFC6636C\n"
" loc_FFC66390:\n"
"                 MOV     R0, R5\n"
"                 BL      sub_FFD31A1C\n"
"                 B       loc_FFC66304\n"
 );
}

void __attribute__((naked,noinline)) sub_FFC65828_my(){ 
 asm volatile(
"                 STMFD   SP!, {R4-R8,LR}\n"
"                 MOV     R7, R1\n"
"                 MOV     R4, R0\n"
"                 BL      sub_FFC67080\n"
"                 LDR     R5, =0x5A84\n"
"                 LDR     R3, =0x200A\n"
"                 LDR     R12, [R5]\n"
"                 LDR     R2, =0x4008\n"
"                 LDR     R6, =0x9A3\n"
"                 LDR     R0, =0x3007\n"
"                 LDR     R1, =0x1051\n"
"                 CMP     R12, #9\n"
"                 ADD     LR, R3, #0x15\n"
"                 ADDLS   PC, PC, R12,LSL#2\n"
"                 B       loc_FFC66FAC\n"
" loc_FFC66D20:\n"
"                 B       loc_FFC66D48\n"
" loc_FFC66D24:\n"
"                 B       loc_FFC66D58\n"
" loc_FFC66D28:\n"
"                 B       loc_FFC66D68\n"
" loc_FFC66D2C:\n"
"                 B       loc_FFC66DDC\n"
" loc_FFC66D30:\n"
"                 B       loc_FFC66E1C\n"
" loc_FFC66D34:\n"
"                 B       loc_FFC66E90\n"
" loc_FFC66D38:\n"
"                 B       loc_FFC66ED0\n"
" loc_FFC66D3C:\n"
"                 B       loc_FFC66F80\n"
" loc_FFC66D40:\n"
"                 B       loc_FFC66F44\n"
" loc_FFC66D44:\n"
"                 B       loc_FFC66FB4\n"
" loc_FFC66D48:\n"
"                 MOV     R1, R7\n"
"                 MOV     R0, R4\n"
"                 LDMFD   SP!, {R4-R8,LR}\n"
"                 B       sub_FFC66C60\n"
" loc_FFC66D58:\n"
"                 MOV     R1, R7\n"
"                 MOV     R0, R4\n"
"                 LDMFD   SP!, {R4-R8,LR}\n"
"                 B       sub_FFC671E4_my\n"
" loc_FFC66D68:\n"
"                 CMP     R4, R1\n"
"                 BEQ     loc_FFC66DCC\n"
"                 SUB     R12, R4, #0x2000\n"
"                 SUBS    R12, R12, #6\n"
"                 BEQ     loc_FFC66D90\n"
"                 CMP     R4, R0\n"
"                 BEQ     loc_FFC66DD4\n"
"                 SUB     R12, R4, #0x3100\n"
"                 SUBS    R12, R12, #0x4B\n"
"                 BNE     loc_FFC66FAC\n"
" loc_FFC66D90:\n"
"                 BL      sub_FFC66258\n"
"                 MOV     R0, #0\n"
"                 BL      sub_FFC67068\n"
"                 LDR     R0, [R5,#8]\n"
"                 CMP     R0, #0\n"
"                 MOVNE   R1, #0\n"
"                 MOVNE   R0, R6\n"
"                 BNE     loc_FFC66DC4\n"
"                 LDR     R0, [R5,#4]\n"
"                 CMP     R0, #0\n"
"                 BEQ     loc_FFC66FA4\n"
"                 LDR     R0, =0x9A1\n"
"                 MOV     R1, #0\n"
" loc_FFC66DC4:\n"
"                 BL      sub_FFC66C60\n"
"                 B       loc_FFC66FA4\n"
" loc_FFC66DCC:\n"
"                 BL      sub_FFC67158\n"
"                 B       loc_FFC66FA4\n"
" loc_FFC66DD4:\n"
"                 BL      sub_FFC67170\n"
"                 B       loc_FFC66FA4\n"
" loc_FFC66DDC:\n"
"                 SUB     R12, R4, #0x900\n"
"                 SUBS    R12, R12, #0xA2\n"
"                 BEQ     loc_FFC66E0C\n"
"                 CMP     R4, R6\n"
"                 BEQ     loc_FFC66E04\n"
"                 CMP     R4, R1\n"
"                 BEQ     loc_FFC66E14\n"
"                 CMP     R4, R0\n"
"                 BLEQ    sub_FFC67170\n"
"                 B       loc_FFC66FAC\n"
" loc_FFC66E04:\n"
"                 BL      sub_FFC66C04_my\n"
"                 B       loc_FFC66FAC\n"
" loc_FFC66E0C:\n"
"                 BL      sub_FFC67134\n"
"                 B       loc_FFC66FAC\n"
" loc_FFC66E14:\n"
"                 BL      sub_FFC67158\n"
"                 B       loc_FFC66FAC\n"
" loc_FFC66E1C:\n"
"                 CMP     R4, LR\n"
"                 BEQ     loc_FFC66E70\n"
"                 BGT     loc_FFC66E44\n"
"                 CMP     R4, R6\n"
"                 BEQ     loc_FFC66E58\n"
"                 CMP     R4, R1\n"
"                 BNE     loc_FFC66EA4\n"
"                 BL      sub_FFC15DB4\n"
"                 BL      sub_FFC671C0\n"
"                 B       loc_FFC66ED8\n"
" loc_FFC66E44:\n"
"                 CMP     R4, R0\n"
"                 BNE     loc_FFC66EB8\n"
"                 BL      sub_FFC15DB4\n"
"                 BL      sub_FFC671C0\n"
"                 B       loc_FFC66F78\n"
" loc_FFC66E58:\n"
"                 BL      sub_FFC15DB4\n"
"                 MOV     R0, #5\n"
"                 BL      sub_FFC67068\n"
"                 MOV     R0, #0\n"
"                 STR     R0, [R5,#0xC]\n"
"                 B       loc_FFC66FA4\n"
" loc_FFC66E70:\n"
"                 MOV     R0, #5\n"
"                 BL      sub_FFC67068\n"
"                 B       loc_FFC66EC4\n"
" loc_FFC66E7C:\n"
"                 BL      sub_FFC671C0\n"
"                 BL      sub_FFC67134\n"
"                 B       loc_FFC66FA4\n"
" loc_FFC66E88:\n"
"                 BL      sub_FFC67068\n"
"                 B       loc_FFC66FA4\n"
" loc_FFC66E90:\n"
"                 CMP     R4, LR\n"
"                 BEQ     loc_FFC66EC4\n"
"                 BGT     loc_FFC66EB0\n"
"                 CMP     R4, R1\n"
"                 BEQ     loc_FFC66ED8\n"
" loc_FFC66EA4:\n"
"                 CMP     R4, R3\n"
"                 BEQ     loc_FFC66E7C\n"
"                 B       loc_FFC66FAC\n"
" loc_FFC66EB0:\n"
"                 CMP     R4, R0\n"
"                 BEQ     loc_FFC66F78\n"
" loc_FFC66EB8:\n"
"                 CMP     R4, R2\n"
"                 BEQ     loc_FFC66E7C\n"
"                 B       loc_FFC66FAC\n"
" loc_FFC66EC4:\n"
"                 MOV     R0, R7\n"
"                 BL      sub_FFC6718C\n"
"                 B       loc_FFC66FA4\n"
" loc_FFC66ED0:\n"
"                 CMP     R4, R1\n"
"                 BNE     loc_FFC66FAC\n"
" loc_FFC66ED8:\n"
"                 MOV     R0, #8\n"
"                 B       loc_FFC66E88\n"
" loc_FFC66F44:\n"
"                 CMP     R4, R0\n"
"                 BEQ     loc_FFC66F78\n"
"                 BGT     loc_FFC66F64\n"
"                 CMP     R4, R3\n"
"                 BEQ     loc_FFC66DCC\n"
"                 CMP     R4, LR\n"
"                 BEQ     loc_FFC66EC4\n"
"                 B       loc_FFC66FAC\n"
" loc_FFC66F64:\n"
"                 CMP     R4, R2\n"
"                 SUBNE   R12, R4, #0x4000\n"
"                 SUBNES  R12, R12, #0xE\n"
"                 BEQ     loc_FFC66DCC\n"
"                 B       loc_FFC66FAC\n"
" loc_FFC66F78:\n"
"                 MOV     R0, #7\n"
"                 B       loc_FFC66E88\n"
" loc_FFC66F80:\n"
"                 CMP     R4, R3\n"
"                 BEQ     loc_FFC66F98\n"
"                 CMP     R4, LR\n"
"                 BEQ     loc_FFC66EC4\n"
"                 CMP     R4, R2\n"
"                 BNE     loc_FFC66FAC\n"
" loc_FFC66F98:\n"
"                 BL      sub_FFC67134\n"
"                 MOV     R0, #0\n"
"                 BL      sub_FFC6639C\n"
" loc_FFC66FA4:\n"
"                 MOV     R0, #0\n"
"                 LDMFD   SP!, {R4-R8,PC}\n"
" loc_FFC66FAC:\n"
"                 MOV     R0, #1\n"
"                 LDMFD   SP!, {R4-R8,PC}\n"
" loc_FFC66FB4:\n"
"                 MOV     R1, R7\n"
"                 MOV     R0, R4\n"
"                 LDMFD   SP!, {R4-R8,LR}\n"
"                 B       sub_FFC67310_my\n"
);
}


void __attribute__((naked,noinline)) sub_FFC67310_my(){ 
asm volatile (
"                 LDR     R12, =0x1077\n"
"                 STMFD   SP!, {R4-R6,LR}\n"
"                 LDR     R5, =0x852\n"
"                 CMP     R0, R12\n"
"                 MOV     R4, R0\n"
"                 BEQ     loc_FFC6739C\n"
"                 BGT     loc_FFC67358\n"
"                 CMP     R4, R5\n"
"                 BEQ     loc_FFC6739C\n"
"                 SUB     R12, R4, #0x1000\n"
"                 SUBS    R12, R12, #0x51\n"
"                 BEQ     loc_FFC673EC\n"
"                 SUB     R12, R4, #0x1000\n"
"                 SUBS    R12, R12, #0x71\n"
"                 SUBNE   R12, R4, #0x1000\n"
"                 SUBNES  R12, R12, #0x72\n"
"                 BNE     loc_FFC673D0\n"
"                 B       loc_FFC6739C\n"
" loc_FFC67358:\n"
"                 SUB     R12, R4, #0x1000\n"
"                 SUBS    R12, R12, #0x78\n"
"                 BEQ     loc_FFC6739C\n"
"                 SUB     R12, R4, #0x3000\n"
"                 SUBS    R12, R12, #7\n"
"                 BEQ     loc_FFC673D8\n"
"                 SUB     R12, R4, #0x3100\n"
"                 SUBS    R12, R12, #0x2A\n"
"                 BNE     loc_FFC673D0\n"
"                 BL      sub_FFC67404\n"
"                 LDR     R0, =0x5A84\n"
"                 LDR     R0, [R0,#0x14]\n"
"                 CMP     R0, #0\n"
"                 BNE     loc_FFC673FC\n"
"                 BL      sub_FFC67108_my\n"
"                 BL      sub_FFD32AD0\n"
"                 B       loc_FFC673FC\n"
" loc_FFC6739C:\n"
"                 BL      sub_FFC67404\n"
"                 CMP     R4, R5\n"
"                 LDREQ   R0, =0x8008\n"
"                 MOVEQ   R1, #0\n"
"                 BLEQ    sub_FFC5D6A8\n"
"                 BL      sub_FFD319D0\n"
"                 BL      sub_FFC67134\n"
"                 BL      sub_FFD32AD0\n"
"                 BL      sub_FFC66258\n"
"                 MOV     R0, #0\n"
"                 BL      sub_FFC67068\n"
"                 CMP     R4, R5\n"
"                 BEQ     loc_FFC673FC\n"
" loc_FFC673D0:\n"
"                 MOV     R0, #1\n"
"                 LDMFD   SP!, {R4-R6,PC}\n"
" loc_FFC673D8:\n"
"                 BL      sub_FFC67404\n"
"                 BL      sub_FFD319D0\n"
"                 BL      sub_FFD32AD0\n"
"                 BL      sub_FFC67170\n"
"                 B       loc_FFC673FC\n"
" loc_FFC673EC:\n"
"                 BL      sub_FFC67404\n"
"                 BL      sub_FFD319D0\n"
"                 BL      sub_FFD32AD0\n"
"                 BL      sub_FFC67158\n"
" loc_FFC673FC:\n"
"                 MOV     R0, #0\n"
"                 LDMFD   SP!, {R4-R6,PC}\n"

 );
} 


void __attribute__((naked,noinline)) sub_FFC671E4_my(){ 
 asm volatile(
"                 LDR     R3, =0x5A84\n"
"                 LDR     R12, =0x2006\n"
"                 STMFD   SP!, {R4,LR}\n"
"                 LDR     R1, [R3,#0xC]\n"
"                 LDR     R2, [R3,#0x14]\n"
"                 CMP     R0, R12\n"
"                 BEQ     loc_FFC67258\n"
"                 BGT     loc_FFC67224\n"
"                 SUB     R12, R0, #0x900\n"
"                 SUBS    R12, R12, #0xA2\n"
"                 BEQ     loc_FFC6727C\n"
"                 SUB     R12, R0, #0x1000\n"
"                 SUBS    R12, R12, #0x51\n"
"                 BNE     loc_FFC672A0\n"
"                 BL      sub_FFC67158\n"
"                 B       loc_FFC67298\n"
" loc_FFC67224:\n"
"                 SUB     R12, R0, #0x3000\n"
"                 SUBS    R12, R12, #7\n"
"                 BEQ     loc_FFC67294\n"
"                 SUB     R12, R0, #0x3100\n"
"                 SUBS    R12, R12, #0x4B\n"
"                 BNE     loc_FFC672A0\n"
"                 CMP     R2, #0\n"
"                 BNE     loc_FFC67298\n"
"                 LDR     R0, [R3,#8]\n"
"                 ORRS    R0, R0, R1\n"
"                 BEQ     loc_FFC67264\n"
"                 BL      sub_FFC66C04_my\n"
"                 B       loc_FFC67298\n"
" loc_FFC67258:\n"
"                 CMP     R2, #0\n"
"                 BLEQ    sub_FFC6598C\n"
"                 B       loc_FFC67298\n"
" loc_FFC67264:\n"
"                 LDR     R0, [R3,#4]\n"
"                 CMP     R0, #0\n"
"                 MOVNE   R0, #3\n"
"                 BNE     loc_FFC6728C\n"
"                 BL      sub_FFC67134\n"
"                 B       loc_FFC67298\n"
" loc_FFC6727C:\n"
"                 CMP     R1, #0\n"
"                 BNE     loc_FFC67298\n"
"                 BL      sub_FFC158B8\n"
"                 MOV     R0, #2\n"
" loc_FFC6728C:\n"
"                 BL      sub_FFC67068\n"
"                 B       loc_FFC67298\n"
" loc_FFC67294:\n"
"                 BL      sub_FFC67170\n"
" loc_FFC67298:\n"
"                 MOV     R0, #0\n"
"                 LDMFD   SP!, {R4,PC}\n"
" loc_FFC672A0:\n"
"                 MOV     R0, #1\n"
"                 LDMFD   SP!, {R4,PC}\n"
 );
} 





void __attribute__((naked,noinline)) sub_FFC66C04_my(){ 
 asm volatile(
"                 STMFD   SP!, {R4,LR}\n"
"                 ADR     R1, a_entryactionon ; "_EntryActionOnPreMoving"\n"
"                 MOV     R0, #0x60\n"
"                 BL      sub_FFC5673C\n"
"                 LDR     R4, =0x5A84\n"
"                 LDR     R0, [R4,#0x10]\n"
"                 CMP     R0, #0\n"
"                 LDMEQFD SP!, {R4,LR}\n"
"                 BEQ     sub_FFC67108_my\n"
"                 ADR     R1, a_entryaction_0 ; "_EntryActionOnSelfTimer"\n"
"                 MOV     R0, #0x60\n"
"                 BL      sub_FFC5673C\n"
"                 BL      sub_FFD32AFC\n"
"                 LDR     R0, [R4,#0x18]\n"
"                 CMP     R0, #1\n"
"                 MOVNE   R0, #1\n"
"                 STRNE   R0, [R4,#0x18]\n"
"                 BLNE    LockMainPower\n"
"                 MOV     R0, #9\n"
"                 BL      sub_FFC67068\n"
"                 LDMFD   SP!, {R4,LR}\n"
"                 B       sub_FFD31884\n"
 );
} 





void __attribute__((naked,noinline)) sub_FFC67108_my(){ 
 asm volatile(
"                 STMFD   SP!, {R4,LR}\n"
"                 ADR     R1, a_entryaction_1 ; "_EntryActionOnMoving"\n"
"                 MOV     R0, #0x60\n"
"                 BL      sub_FFC5673C\n"
"                 LDR     R1, =0x5A84\n"
"                 MOV     R0, #0\n"
"                 STR     R0, [R1,#0xC]\n"
"                 MOV     R0, #4\n"
"                 BL      sub_FFC67068\n"
"                 LDMFD   SP!, {R4,LR}\n"
"                 B       sub_FFC668C4_my\n"
 );
} 

void __attribute__((naked,noinline)) sub_FFC668C4_my(){ 
 asm volatile(
"                 LDR     R0, =0x5A40\n"
"                 STMFD   SP!, {R3,LR}\n"
"                 LDR     R1, [R0,#0x40]\n"
"                 CMP     R1, #1\n"
"                 MOVNE   R1, #1\n"
"                 STRNE   R1, [R0,#0x40]\n"
"                 BLNE    LockMainPower\n"
"                 MOV     R1, #0\n"
"                 MOV     R0, #0x80\n"
"                 BL      sub_FFC676C4\n"
"                 MOV     R2, #2\n"
"                 MOV     R1, SP\n"
"                 MOV     R0, #0x6B\n"
"                 BL      PT_GetPropertyCaseString\n"
"                 MOV     R2, #2\n"
"                 MOV     R1, SP\n"
"                 MOV     R0, #0xA3\n"
"                 BL      PT_SetPropertyCaseString\n"
"                 BL      sub_FFC48D3C\n"
"                 BL      sub_FFC65C58\n"
"                 BL      sub_FFC15D78_my\n"
"                 BL      sub_FFC66210\n"
"                 LDMFD   SP!, {R12,PC}\n"
 );
} 





void __attribute__((naked,noinline)) sub_FFC15D78_my(){ 
 asm volatile(
"                 STMFD   SP!, {R4,LR}\n"
"                 MOV     R4, R0\n"
"                 MOV     R0, #0x120\n"
"                 ADR     R1, aMovierecStart ; "MovieRec Start"\n"
"                 BL      sub_FFC5673C\n"
"                 BL      sub_FFC160B4\n"
"                 CMP     R0, #0\n"
"                 LDMNEFD SP!, {R4,PC}\n"
"                 MOV     R0, #4\n"
"                 BL      sub_FFC462C8\n"
"                 BL      sub_FFC49FE4\n"
"                 LDR     R0, =0x18C90\n"
"                 STR     R4, [R0,#0x4C]\n"
"                 LDMFD   SP!, {R4,LR}\n"
"                 B       sub_FFC4AE9C_my\n"
 );
} 








void __attribute__((naked,noinline)) sub_FFC4AE9C_my(){ 
 asm volatile(
                "STMFD   SP!, {R4-R8,LR}\n"
                "MOV     R8, R0\n"
                "MOV     R0, #0x41\n"
                "SUB     SP, SP, #0x38\n"
                "MOV     R5, #0\n"
                "STR     R0, [SP,#0x34]\n"
                "BL      sub_FFC4DB28\n"
                "CMP     R0, #0\n"
                "LDRNE   R1, =0x13B\n"
                "BNE     loc_FFC4DD04\n"
                "LDR     R4, =0x56B8\n"
                "MOV     R1, #0x1E\n"
                "LDR     R0, [R4,#0xC]\n"
                "BL      sub_FFC18E20\n"
                "BL      sub_FFC59DBC\n"
                "STR     R0, [R4,#4]\n"
                "MOV     R0, #0\n"
                "BL      sub_FFC55F0C\n"
                "STR     R0, [SP,#0x28]\n"
                "ADD     R0, SP, #0x28\n"
                "MOV     R1, SP\n"
                "BL      sub_FFC56058\n"
                "MOV     R0, SP\n"
                "BL      sub_FFC55F40\n"
                "STR     R0, [SP,#0x2C]\n"
                "LDR     R0, [R4,#4]\n"
                "MOV     R3, #4\n"
                "ADD     R2, SP, #0x2C\n"
                "MOV     R1, #0x34\n"
                "BL      sub_FFC5A0DC\n"
                "LDR     R7, [SP,#0x2C]\n"
                "BL      sub_FFC4E080\n"
                "MOV     R6, #0\n"
                "ADD     R1, SP, #0x28\n"
                "ADD     R0, SP, #0x2C\n"
                "STR     R6, [SP,#0x2C]\n"
                "STR     R6, [SP,#0x28]\n"
                "BL      sub_FFC21C3C\n"
                "LDR     R0, [R4,#4]\n"
                "MOV     R3, #2\n"
                "ADD     R2, SP, #0x2C\n"
                "MOV     R1, #0x2F\n"
                "BL      sub_FFC5A0DC\n"
                "LDR     R0, [R4,#4]\n"
                "MOV     R3, #2\n"
                "ADD     R2, SP, #0x28\n"
                "MOV     R1, #0x2D\n"
                "BL      sub_FFC5A0DC\n"
                "ADD     R1, SP, #0x28\n"
                "ADD     R0, SP, #0x2C\n"
                "BL      sub_FFC24B70\n"
                "LDR     R0, [R4,#4]\n"
                "MOV     R3, #2\n"
                "ADD     R2, SP, #0x2C\n"
                "MOV     R1, #0x30\n"
                "BL      sub_FFC5A0DC\n"
                "ADD     R1, SP, #0x28\n"
                "ADD     R0, SP, #0x2C\n"
                "BL      sub_FFC22400\n"
                "LDR     R0, [R4,#4]\n"
                "MOV     R3, #2\n"
                "ADD     R2, SP, #0x28\n"
                "MOV     R1, #0x2E\n"
                "BL      sub_FFC5A0DC\n"
                "LDR     R0, [R4,#4]\n"
                "MOV     R3, #2\n"
                "ADD     R2, SP, #0x2C\n"
                "MOV     R1, #0xB8\n"
                "BL      sub_FFC5A188\n"
                "TST     R0, #1\n"
                "LDRNE   R1, =0x11D\n"
                "LDRNE   R0, =0xFFC4DF7C\n"
                "BLNE    sub_FFC0C098\n"
                "LDRH    R0, [SP,#0x2C]\n"
                "MOV     R3, #4\n"
                "ADD     R2, SP, #0x28\n"
                "CMP     R0, #0\n"
                "MOVNE   R0, #1\n"
                "STR     R0, [SP,#0x28]\n"
                "LDR     R0, [R4,#4]\n"
                "MOV     R1, #0x92\n"
                "BL      sub_FFC5A0DC\n"
                "MOV     R2, #1\n"
                "ADD     R1, SP, #0x34\n"
                "MOV     R0, #0xFA\n"
                "BL      sub_FFC59C2C\n"
                "TST     R0, #1\n"
                "LDRNE   R1, =0x152\n"
                "LDRNE   R0, =0xFFC4DF7C\n"
                "BLNE    sub_FFC0C098\n"
                "LDRB    R0, [SP,#0x34]\n"
                "MOV     R3, R8\n"
                "MOV     R2, #0x14\n"
                "AND     R1, R0, #0xFF\n"
                "ADD     R0, SP, #0x30\n"
                "STR     R7, [SP]\n"
                "BL      sub_FFCE6924\n"
                "TST     R0, #1\n"
                "LDRNE   R1, =0x156\n"
                "BNE     loc_FFC4DD04\n"
                "LDR     R0, =0x1926C\n"
                "LDR     R1, [SP,#0x30]\n"
                "MOV     R2, #0x10\n"
                "BL      sub_FFCDCDE8\n"
                "TST     R0, #1\n"
                "BEQ     loc_FFC4DD14\n"
                "LDR     R1, =0x15E\n"
"loc_FFC4DD04:\n"
                "LDR     R0, =0xFFC4DF7C\n"
                "BL      sub_FFC0C098\n"
"loc_FFC4DD0C:\n"
                "ADD     SP, SP, #0x38\n"
                "LDMFD   SP!, {R4-R8,PC}\n"
"loc_FFC4DD14:\n"
                "LDR     R0, [R4,#4]\n"
                "MOV     R3, #4\n"
                "ADD     R2, SP, #0x30\n"
                "MOV     R1, #0x2B\n"
                "BL      sub_FFC5A0DC\n"
                "BL      sub_FFC674DC\n"
                "LDRSB   R1, [SP,#0x34]\n"
                "CMP     R0, R1\n"
                "MOVEQ   R7, #0\n"
                "BEQ     loc_FFC4DD68\n"
                "LDR     R5, =0x1926C\n"
                "MOV     R0, R5\n"
                "BL      sub_FFC67658\n"
                "MOV     R8, R0\n"
                "BL      sub_FFC959E4\n"
                "CMP     R8, R0\n"
                "MOV     R7, R0\n"
                "LDRLS   R1, =0x16B\n"
                "LDRLS   R0, =0xFFC4DF7C\n"
                "BLLS    sub_FFC0C098\n"
                "SUB     R7, R8, R7\n"
"loc_FFC4DD68:\n"
                "BL      sub_FFC49C20_my\n"   //----------------------->
                "LDR     R0, =0x19290\n"
                "LDRH    R3, [R0,#0x46]\n"
                "LDRH    R2, [R0,#0x44]\n"
                "LDR     R1, [R0,#0x40]\n"
                "LDR     R0, [R0,#0x3C]\n"
                "BL      sub_FFC48CA0\n"
                "MOV     R3, #0\n"
                "LDR     R2, =0xFFC4DAF0\n"
                "MOV     R1, #0\n"
                "LDR     R0, =0xFFC4DB04\n"
                "ADD     R8, SP, #0xC\n"
                "STMIA   R8, {R0-R3}\n"
                "LDR     R2, =0xFFC4DB14\n"
                "LDR     R1, =0xFFC4DB00\n"
                "STMEA   SP, {R1-R3}\n"
                "LDR     R1, [R4,#4]\n"
                "MOV     R3, R6\n"
                "MOV     R2, R7\n"
                "MOV     R0, R5\n"
                "BL      sub_FFC48FFC\n"
                "LDR     R0, [R4,#0xC]\n"
                "MOV     R1, #0x20\n"
                "BL      sub_FFC18DEC\n"
                "B       loc_FFC4DD0C\n"
 );
} 


void __attribute__((naked,noinline)) sub_FFC49C20_my(){ 
 asm volatile(
                "STMFD   SP!, {R3-R9,LR}\n"
                "LDR     R5, =0x5538\n"
                "MOV     R6, #0\n"
                "STR     R6, [R5,#0x20]\n"
                "LDR     R0, [R5,#4]\n"
                "LDR     R8, =0x2710\n"
                "CMP     R0, #0\n"
                "BNE     loc_FFC49CD8\n"
                "MOV     R0, #1\n"
                "STR     R0, [R5,#4]\n"
                "MOV     R0, #0\n"
                "MOV     R1, #0\n"
                "BL      sub_FFC0BF14\n"
                "STR     R0, [R5,#0x10]\n"
                "MOV     R0, #0\n"
                "MOV     R1, #0\n"
                "BL      sub_FFC0BF14\n"
                "STR     R0, [R5,#0x14]\n"
                "MOV     R0, #0\n"
                "MOV     R1, #0xA\n"
                "BL      sub_FFC0BECC\n"
                "STR     R0, [R5,#0x18]\n"
                "MOV     R0, #0\n"
                "MOV     R1, #0xA\n"
                "BL      sub_FFC0BECC\n"
                "LDR     R7, =0x18E70\n"
                "MOV     R4, #9\n"
                "ADD     R9, R4, #0x2D4\n"
                "STR     R0, [R5,#0x1C]\n"
"loc_FFC49C94:\n"
                "RSB     R0, R4, R4,LSL#3\n"
                "STR     R6, [R7,R0,LSL#2]\n"
                "ADD     R1, R7, R0,LSL#2\n"
                "STR     R9, [SP]\n"
                "LDR     R0, [R5,#0x1C]\n"
                "LDR     R3, =0xFFC48F9C\n"
                "MOV     R2, R8\n"
                "BL      sub_FFC0BFD8\n"
                "SUBS    R4, R4, #1\n"
                "BPL     loc_FFC49C94\n"
                "MOV     R3, #0\n"
                "STR     R3, [SP]\n"
                "LDR     R3, =MovieRecord_Task_my\n"    // ----------------->
                "MOV     R2, #0x1000\n"
                "MOV     R1, #0x14\n"
                "LDR     R0, =0xFFC49E28\n"    // "Movierecord"
                "BL      sub_FFC0BE98\n"
"loc_FFC49CD8:\n"
                "BL      sub_FFD071E4\n"
                "BL      sub_FFC49D3C\n"
                "MOV     R1, R0\n"
                "MOV     R0, #0xB\n"
                "ADD     R3, R0, #0x2DC\n"
                "STR     R0, [R1]\n"
                "STR     R3, [SP]\n"
                "LDR     R3, =0xFFC48F9C\n"
                "MOV     R2, R8\n"
                "LDR     R0, [R5,#0x18]\n"
                "BL      sub_FFC0BFD8\n"
                "LDMFD   SP!, {R3-R9,PC}\n"
 );
} 


void __attribute__((naked,noinline)) MovieRecord_Task_my(){ 
 asm volatile(
                "STMFD   SP!, {R2-R8,LR}\n"
                "LDR     R8, =0x32B\n"
                "LDR     R7, =0x2710\n"
                "LDR     R4, =0x5538\n"
                "MOV     R6, #0\n"
                "MOV     R5, #1\n"
"loc_FFC49B30:\n"
                "LDR     R0, [R4,#0x18]\n"
                "MOV     R2, #0\n"
                "ADD     R1, SP, #4\n"
                "BL      sub_FFC19070\n"
                "LDR     R0, [R4,#0x20]\n"
                "CMP     R0, #0\n"
                "BNE     loc_FFC49C00\n"
                "LDR     R0, [SP,#4]\n"
                "LDR     R1, [R0]\n"
                "SUB     R1, R1, #2\n"
                "CMP     R1, #9\n"
                "ADDLS   PC, PC, R1,LSL#2\n"
                "B       loc_FFC49C00\n"
"loc_FFC49B64:\n"
                "B       loc_FFC49BB4\n"
"loc_FFC49B68:\n"
                "B       loc_FFC49BD4\n"
"loc_FFC49B6C:\n"
                "B       loc_FFC49BE4\n"
"loc_FFC49B70:\n"
                "B       loc_FFC49BEC\n"
"loc_FFC49B74:\n"
                "B       loc_FFC49BBC\n"
"loc_FFC49B78:\n"
                "B       loc_FFC49BF4\n"
"loc_FFC49B7C:\n"
                "B       loc_FFC49BC4\n"
"loc_FFC49B80:\n"
                "B       loc_FFC49C00\n"
"loc_FFC49B84:\n"
                "B       loc_FFC49BFC\n"
"loc_FFC49B88:\n"
                "B       loc_FFC49B8C\n"
"loc_FFC49B8C:\n"
                "LDR     R0, =0xFFC49814\n"
                "STR     R6, [R4,#0x34]\n"
                "STR     R0, [R4,#0xA0]\n"
                "LDR     R0, =0xFFC4928C\n"
                "LDR     R2, =0xFFC491A8\n"
                "LDR     R1, =0x18F98\n"
                "STR     R6, [R4,#0x24]\n"
                "BL      sub_FFC2B58C\n"
                "STR     R5, [R4,#0x38]\n"
                "B       loc_FFC49C00\n"
"loc_FFC49BB4:\n"
                "BL      unlock_optical_zoom\n" //  +
                "BL      sub_FFC4990C\n"
                "B       loc_FFC49C00\n"
"loc_FFC49BBC:\n"
                "BL      sub_FFC49614_my\n"  //------------------->
                "B       loc_FFC49C00\n"
"loc_FFC49BC4:\n"
                "LDR     R1, [R0,#0x10]\n"
                "LDR     R0, [R0,#4]\n"
                "BL      sub_FFD07DF0\n"
                "B       loc_FFC49C00\n"
"loc_FFC49BD4:\n"
                "LDR     R0, [R4,#0x38]\n"
                "CMP     R0, #5\n"
                "STRNE   R5, [R4,#0x28]\n"
                "B       loc_FFC49C00\n"
"loc_FFC49BE4:\n"
                "BL      sub_FFC4941C\n"
                "B       loc_FFC49C00\n"
"loc_FFC49BEC:\n"
                "BL      sub_FFC492D8\n"
                "B       loc_FFC49C00\n"
"loc_FFC49BF4:\n"
                "BL      sub_FFC49134\n"
                "B       loc_FFC49C00\n"
"loc_FFC49BFC:\n"
                "BL      sub_FFC49D68\n"
"loc_FFC49C00:\n"
                "LDR     R1, [SP,#4]\n"
                "LDR     R3, =0xFFC48F9C\n"
                "STR     R6, [R1]\n"
                "STR     R8, [SP]\n"
                "LDR     R0, [R4,#0x1C]\n"
                "MOV     R2, R7\n"
                "BL      sub_FFC0BFD8\n"
                "B       loc_FFC49B30\n"
 );
} 


void __attribute__((naked,noinline)) sub_FFC49614_my(){ 
 asm volatile(                                   	
                "STMFD   SP!, {R4-R8,LR}\n"
                "SUB     SP, SP, #0x40\n"
                "MOV     R6, #0\n"
                "LDR     R5, =0x5538\n"
                "MOV     R4, R0\n"
                "STR     R6, [SP,#0x30]\n"
                "STR     R6, [SP,#0x28]\n"
                "LDR     R0, [R5,#0x38]\n"
                "MOV     R8, #4\n"
                "CMP     R0, #3\n"
                "STREQ   R8, [R5,#0x38]\n"
                "LDR     R0, [R5,#0xA0]\n"
          //    "BLX     R0\n"                   
                ".long   0xE12FFF30\n"
                "LDR     R0, [R5,#0x38]\n"
                "CMP     R0, #4\n"
                "BNE     loc_FFC496EC\n"
                "ADD     R3, SP, #0x28\n"
                "ADD     R2, SP, #0x2C\n"
                "ADD     R1, SP, #0x30\n"
                "ADD     R0, SP, #0x34\n"
                "BL      sub_FFD07F84\n"
                "CMP     R0, #0\n"
                "MOV     R7, #1\n"
                "BNE     loc_FFC49690\n"
                "LDR     R1, [R5,#0x28]\n"
                "CMP     R1, #1\n"
                "BNE     loc_FFC496F4\n"
                "LDR     R1, [R5,#0x50]\n"
                "LDR     R2, [R5,#0x3C]\n"
                "CMP     R1, R2\n"
                "BCC     loc_FFC496F4\n"
"loc_FFC49690:\n"
                "CMP     R0, #0x80000001\n"
                "STREQ   R8, [R5,#0x54]\n"
                "BEQ     loc_FFC496C8\n"
                "CMP     R0, #0x80000003\n"
                "STREQ   R7, [R5,#0x54]\n"
                "BEQ     loc_FFC496C8\n"
                "CMP     R0, #0x80000005\n"
                "MOVEQ   R0, #2\n"
                "BEQ     loc_FFC496C4\n"
                "CMP     R0, #0x80000007\n"
                "STRNE   R6, [R5,#0x54]\n"
                "BNE     loc_FFC496C8\n"
                "MOV     R0, #3\n"
"loc_FFC496C4:\n"
                "STR     R0, [R5,#0x54]\n"
"loc_FFC496C8:\n"
                "LDR     R0, =0x18FC8\n"
                "LDR     R0, [R0,#8]\n"
                "CMP     R0, #0\n"
                "BEQ     loc_FFC496E0\n"
                "BL      sub_FFC38054\n"
                "B       loc_FFC496E4\n"
"loc_FFC496E0:\n"
                "BL      sub_FFC49134\n"
"loc_FFC496E4:\n"
                "MOV     R0, #5\n"
                "STR     R0, [R5,#0x38]\n"
"loc_FFC496EC:\n"
                "ADD     SP, SP, #0x40\n"
                "LDMFD   SP!, {R4-R8,PC}\n"
"loc_FFC496F4:\n"
                "LDR     LR, [SP,#0x30]\n"
                "CMP     LR, #0\n"
                "BEQ     loc_FFC497BC\n"
                "STR     R7, [R5,#0x2C]\n"
                "LDR     R0, [R5,#0x6C]\n"
                "LDR     R1, [R4,#0x14]\n"
                "LDR     R2, [R4,#0x18]\n"
                "LDR     R12, [R4,#0xC]\n"
                "ADD     R3, SP, #0x38\n"
                "ADD     R8, SP, #0x14\n"
                "STMIA   R8, {R0-R3}\n"
                "LDR     R3, [R5,#0x58]\n"
                "ADD     R2, SP, #0x3C\n"
                "ADD     R8, SP, #8\n"
            //  "LDRD    R0, [SP,#0x28]\n"      
                ".long   0xE1CD02D8\n"
                "STMIA   R8, {R0,R2,R3}\n"
                "STR     R1, [SP,#4]\n"
                "STR     LR, [SP]\n"
                "LDMIB   R4, {R0,R1}\n"
                "LDR     R3, [SP,#0x34]\n"
                "MOV     R2, R12\n"
                "BL      sub_FFCCD308\n"
                "LDR     R0, [R5,#0x10]\n"
                "MOV     R1, #0x3E8\n"
                "BL      sub_FFC0BA5C\n"
                "CMP     R0, #9\n"
                "BNE     loc_FFC49770\n"
                "BL      sub_FFD08560\n"
                "MOV     R0, #0x90000\n"
                "STR     R7, [R5,#0x38]\n"
                "B       loc_FFC49788\n"
"loc_FFC49770:\n"
                "LDR     R0, [SP,#0x38]\n"
                "CMP     R0, #0\n"
                "BEQ     loc_FFC49790\n"
                "BL      sub_FFD08560\n"
                "MOV     R0, #0xA0000\n"
                "STR     R7, [R5,#0x38]\n"
"loc_FFC49788:\n"
                "BL      sub_FFC5C1F8\n"
                "B       loc_FFC496EC\n"
"loc_FFC49790:\n"
                "BL      sub_FFCCD3CC\n"
                "LDR     R0, [SP,#0x34]\n"
                "LDR     R1, [SP,#0x3C]\n"
                "BL      sub_FFD08308\n"
                "LDR     R0, [R5,#0x4C]\n"
                "LDR     R1, =0x55A4\n"
                "ADD     R0, R0, #1\n"
                "STR     R0, [R5,#0x4C]\n"
                "LDR     R0, [SP,#0x3C]\n"
                "MOV     R2, #0\n"
                "BL      sub_FFD06188_my\n"  //----------------->
"loc_FFC497BC:\n"
                "LDR     R0, [R5,#0x50]\n"
                "ADD     R0, R0, #1\n"
                "STR     R0, [R5,#0x50]\n"
                "LDR     R1, [R5,#0x78]\n"
                "MUL     R0, R1, R0\n"
                "LDR     R1, [R5,#0x74]\n"
                "BL      sub_FFE3CED0\n"
                "MOV     R4, R0\n"
                "BL      sub_FFD08598\n"
                "LDR     R1, [R5,#0x70]\n"
                "CMP     R1, R4\n"
                "BNE     loc_FFC497F8\n"
                "LDR     R0, [R5,#0x30]\n"
                "CMP     R0, #1\n"
                "BNE     loc_FFC4980C\n"
"loc_FFC497F8:\n"
                "LDR     R1, [R5,#0x84]\n"
                "MOV     R0, R4\n"

           //   "BLX     R1\n"                  
                ".long   0xE12FFF31\n"

                "STR     R4, [R5,#0x70]\n"
                "STR     R6, [R5,#0x30]\n"
"loc_FFC4980C:\n"
                "STR     R6, [R5,#0x2C]\n"
                "B       loc_FFC496EC\n"
 );
} 


void __attribute__((naked,noinline)) sub_FFD06188_my(){ 
 asm volatile(
                "STMFD   SP!, {R4-R8,LR}\n"
                "LDR     R4, =0x9E48\n"
                "LDR     LR, [R4]\n"
                "LDR     R2, [R4,#8]\n"
                "CMP     LR, #0\n"
                "LDRNE   R3, [R4,#0xC]\n"
                "MOV     R5, R2\n"
                "CMPNE   R3, #1\n"
                "MOVEQ   R2, #0\n"
                "STREQ   R0, [R4]\n"
                "STREQ   R2, [R4,#0xC]\n"
                "BEQ     loc_FFD06254\n"
                "LDR     R3, [R4,#4]\n"
                "LDR     R7, =table\n"          // *
                "ADD     R12, R3, R3,LSL#1\n"
                "LDR     R3, [R7,R12,LSL#2]\n"
                "ADD     R6, R7, #0x30\n"
                "LDR     R8, [R6,R12,LSL#2]\n"
                "SUB     R3, LR, R3\n"
                "CMP     R3, #0\n"
                "SUB     LR, LR, R8\n"
                "BLE     loc_FFD06210\n"
                "ADD     R12, R7, R12,LSL#2\n"
                "LDR     LR, [R12,#4]\n"
                "CMP     LR, R3\n"
                "ADDGE   R2, R2, #1\n"
                "BGE     loc_FFD06204\n"
                "LDR     R12, [R12,#8]\n"
                "CMP     R12, R3\n"
                "ADDLT   R2, R2, #3\n"
                "ADDGE   R2, R2, #2\n"
"loc_FFD06204:\n"
    //          "CMP     R2, #0x17\n"   // -
    //          "MOVGE   R2, #0x16\n"   // -
                "CMP     R2, #0x1A\n"   // +
                "MOVGE   R2, #0x19\n"   // +
                "B       loc_FFD06244\n"
"loc_FFD06210:\n"
                "CMP     LR, #0\n"
                "BGE     loc_FFD06244\n"
                "ADD     R3, R6, R12,LSL#2\n"
                "LDR     R12, [R3,#4]\n"
                "CMP     R12, LR\n"
                "SUBLE   R2, R2, #1\n"
                "BLE     loc_FFD0623C\n"
                "LDR     R3, [R3,#8]\n"
                "CMP     R3, LR\n"
                "SUBGT   R2, R2, #3\n"
                "SUBLE   R2, R2, #2\n"
"loc_FFD0623C:\n"
                "CMP     R2, #0\n"
                "MOVLT   R2, #0\n"
"loc_FFD06244:\n"
                "CMP     R2, R5\n"
                "STRNE   R2, [R4,#8]\n"
                "MOVNE   R2, #1\n"
                "STRNE   R2, [R4,#0xC]\n"
"loc_FFD06254:\n"
                "LDR     R2, =CompressionRateTable\n"   // *
                "LDR     R3, [R4,#8]\n"
                "LDR     R2, [R2,R3,LSL#2]\n"

                "LDR     R3, =video_mode\n"      // +
                "LDR     R3, [R3]\n"             // +
                "LDR     R3, [R3]\n"             // +
                "CMP     R3, #1\n"               // +
                "LDREQ   R3, =video_quality\n"   // +     
                "LDREQ   R3, [R3]\n"             // +     
                "LDREQ   R2, [R3]\n"             // +     

                "STR     R2, [R1]\n"
                "STR     R0, [R4]\n"
        //        "BL      mute_on_zoom\n"     // +
                "LDMFD   SP!, {R4-R8,PC}\n"
 );
} 

#include "conf.h"

int *video_quality = &conf.video_quality;
int *video_mode    = &conf.video_mode;

long def_table[24]={0x2000, 0x38D, 0x788, 0x5800, 0x9C5, 0x14B8, 0x10000, 0x1C6A, 0x3C45, 0x8000, 0xE35, 0x1E23,
           0x1CCD, -0x2E1, -0x579, 0x4F33, -0x7EB, -0xF0C, 0xE666, -0x170A, -0x2BC6, 0x7333, -0xB85, -0x15E3};

long table[24];

void change_video_tables(int a, int b){
 int i;
 for (i=0;i<24;i++) table[i]=(def_table[i]*a)/b; 
}

long CompressionRateTable[]={0x60, 0x5D, 0x5A, 0x57, 0x54, 0x51, 0x4D, 0x48, 0x42, 0x3B, 0x32, 0x29, 0x22, 0x1D, 0x17, 0x14, 0x10, 0xE, 0xB, 9, 7, 6, 5, 4, 3, 2, 1};
