
NSTUB(eventproc_export_memShow, 0xffc00bf4)

NSTUB(eventproc_export_CreateTask, 0xffc0ad70)

NSTUB(eventproc_export_ExitTask, 0xffc0b000)

NSTUB(eventproc_export_RotateConsoleZOder, 0xffc0b750)

NSTUB(eventproc_export_CPrintf, 0xffc0b960)
NSTUB(eventproc_export_CPutChar, 0xffc0b9bc)
NSTUB(eventproc_export_GetCh, 0xffc0b9e8)
NSTUB(eventproc_export_GetStringWithPrompt, 0xffc0ba38)
NSTUB(eventproc_export_OpenConsole, 0xffc0ba98)
NSTUB(eventproc_export_CloseConsole, 0xffc0bc04)

NSTUB(eventproc_export_StartRedirectUART, 0xffc0c2f8)
NSTUB(eventproc_export_StopRedirectUART, 0xffc0c410)

NSTUB(eventproc_export_sprintf, 0xffc0cabc)

NSTUB(eventproc_export_strcpy, 0xffc0cb3c)
NSTUB(eventproc_export_strcmp, 0xffc0cb54)
NSTUB(eventproc_export_strlen, 0xffc0cb98)
NSTUB(eventproc_export_memcmp, 0xffc0cbbc)

NSTUB(eventproc_export_Fopen_Fut, 0xffc13278)
NSTUB(eventproc_export_Fclose_Fut, 0xffc132b8)
NSTUB(eventproc_export_Fread_Fut, 0xffc13364)
NSTUB(eventproc_export_Fwrite_Fut, 0xffc133b8)

NSTUB(eventproc_export_Fseek_Fut, 0xffc13458)

NSTUB(eventproc_export_Open, 0xffc13868)
NSTUB(eventproc_export_Close, 0xffc13890)

NSTUB(eventproc_export_Read, 0xffc13938)
NSTUB(eventproc_export_Write, 0xffc1393c)

NSTUB(eventproc_export_Lseek, 0xffc13a98)

NSTUB(eventproc_export_StartCameraLog, 0xffc13f60)
NSTUB(eventproc_export_ShowCameraLog, 0xffc13f64)
NSTUB(eventproc_export_ShowCameraLogInfo, 0xffc13f68)
NSTUB(eventproc_export_StopCameraLog, 0xffc13f6c)
NSTUB(eventproc_export_PutsCameraLogEvent, 0xffc13f70)

NSTUB(eventproc_export_NewTaskShell, 0xffc13fd8)

NSTUB(eventproc_export_ExMem, 0xffc13ff0)

NSTUB(eventproc_export_CreateCountingSemaphore, 0xffc168b4)
NSTUB(eventproc_export_DeleteSemaphore, 0xffc1690c)

NSTUB(eventproc_export_TakeSemaphore, 0xffc169b8)
NSTUB(eventproc_export_GiveSemaphore, 0xffc16a88)

NSTUB(eventproc_export_SleepTask, 0xffc16cf0)

NSTUB(eventproc_export_UnLoadScript, 0xffc5a2f0)

NSTUB(eventproc_export_LoadScript, 0xffc5a3ec)

NSTUB(eventproc_export_GetTimeOfSystem, 0xffc5b168)

NSTUB(eventproc_export_OpLog_Show, 0xffc5e5a4)
NSTUB(eventproc_export_OpLog_Stop, 0xffc5e61c)

NSTUB(eventproc_export_OpLog_WriteToROM, 0xffc5e678)

NSTUB(eventproc_export_OpLog_ReadFromROM, 0xffc5e69c)
NSTUB(eventproc_export_OpLog_ReadFromSD, 0xffc5e6e8)
NSTUB(eventproc_export_OpLog_WriteToSD, 0xffc5eb40)
NSTUB(eventproc_export_OpLog_Get, 0xffc5efbc)
NSTUB(eventproc_export_OpLog_Play, 0xffc5f020)

NSTUB(eventproc_export_OpLog_Start, 0xffc5f11c)

NSTUB(eventproc_export_StartWDT, 0xffc5f9e4)
NSTUB(eventproc_export_StopWDT, 0xffc5fa48)

NSTUB(eventproc_export_GetBuildDate, 0xffc5fb38)
NSTUB(eventproc_export_GetBuildTime, 0xffc5fb40)
NSTUB(eventproc_export_GetFirmwareVersion, 0xffc5fb48)

NSTUB(eventproc_export_CheckSumAll, 0xffc5fc54)
NSTUB(eventproc_export_RomCheckSum, 0xffc5fe4c)

NSTUB(eventproc_export_CreateController, 0xffc635ac)
NSTUB(eventproc_export_DeleteController, 0xffc63668)

NSTUB(eventproc_export_MoveControllerToTopOfZOrder, 0xffc637ec)

NSTUB(eventproc_export_GetSelfControllerHandle, 0xffc6391c)

NSTUB(eventproc_export_PostLogicalEventForNotPowerType, 0xffc63d5c)
NSTUB(eventproc_export_PostLogicalEventToUI, 0xffc63da8)
NSTUB(eventproc_export_PostEventShootSeqToUI, 0xffc63e20)
NSTUB(eventproc_export_ShowLogicalEventName, 0xffc63e7c)

NSTUB(eventproc_export_IsControlEventActive, 0xffc65b40)
NSTUB(eventproc_export_UiEvnt_SetLogicalEventActive, 0xffc65bb0)
NSTUB(eventproc_export_SetScriptMode, 0xffc65c00)

NSTUB(eventproc_export_UiEvnt_StartDisguiseCradleStatus, 0xffc65c34)
NSTUB(eventproc_export_UiEvnt_StopDisguiseCradleStatus, 0xffc65c44)

NSTUB(eventproc_export_UnlockMainPower, 0xffc65db4)
NSTUB(eventproc_export_LockMainPower, 0xffc65e60)
NSTUB(eventproc_export_SetAutoShutdownTime, 0xffc65ed4)

NSTUB(eventproc_export_HardwareDefectWithRestart, 0xffc660ac)
NSTUB(eventproc_export_HardwareDefect, 0xffc660fc)

NSTUB(eventproc_export_PTM_AllResetToFactorySetting, 0xffc6630c)
NSTUB(eventproc_export_PTM_AllReset, 0xffc6631c)

NSTUB(eventproc_export_PTM_SetCurrentCaptureMode, 0xffc667a4)

NSTUB(eventproc_export_PTM_GetWorkingCaptureMode, 0xffc6686c)
NSTUB(eventproc_export_PTM_SetCurrentItem, 0xffc66870)

NSTUB(eventproc_export_PTM_GetCurrentItem, 0xffc6687c)

NSTUB(eventproc_export_PTM_NextItem, 0xffc668e8)
NSTUB(eventproc_export_PTM_PrevItem, 0xffc668ec)

NSTUB(eventproc_export_PTM_IsEnableItem, 0xffc668fc)
NSTUB(eventproc_export_PTM_SetProprietyEnable, 0xffc66900)

NSTUB(eventproc_export_PTM_BackupUIProperty, 0xffc66918)
NSTUB(eventproc_export_PTM_RestoreUIProperty, 0xffc6691c)

NSTUB(eventproc_export_SetCurrentCaptureModeType, 0xffc6c288)
NSTUB(eventproc_export_GetCurrentCaptureModeType, 0xffc6c2c4)

NSTUB(eventproc_export_GUISrv_StartGUISystem, 0xffc753ec)

NSTUB(eventproc_export_atol, 0xffc7565c)

NSTUB(eventproc_export_memcpy, 0xffc75854)

NSTUB(eventproc_export_GetLatestHVPosition, 0xffcc7e14)

NSTUB(eventproc_export_SetSDPwrPort, 0xffd149f0)
NSTUB(eventproc_export_GetAdVBattBottom, 0xffd14a1c)
NSTUB(eventproc_export_GetAdChValue, 0xffd14a20)
NSTUB(eventproc_export_BeepDrive, 0xffd14a24)
NSTUB(eventproc_export_BeepDriveComp, 0xffd14a28)
NSTUB(eventproc_export_VbattGet, 0xffd14a2c)
NSTUB(eventproc_export_LEDDrive, 0xffd14a30)
NSTUB(eventproc_export_ShowPhySwStatus, 0xffd14a34)
NSTUB(eventproc_export_SetRawSWCheckMode, 0xffd14a44)
NSTUB(eventproc_export_OnPrintPhySw, 0xffd14a54)
NSTUB(eventproc_export_OffPrintPhySw, 0xffd14a64)
NSTUB(eventproc_export_GetSwitchStatus, 0xffd14a74)
NSTUB(eventproc_export_ShowSDStatus, 0xffd14a78)
NSTUB(eventproc_export_GetSDDetect, 0xffd14a88)
NSTUB(eventproc_export_GetSDProtect, 0xffd14a8c)
NSTUB(eventproc_export_SetIgnoreAVJACK, 0xffd14a90)
NSTUB(eventproc_export_GetDialEventId, 0xffd14aa0)
NSTUB(eventproc_export_GetBatteryCoverClose, 0xffd14aa4)

NSTUB(eventproc_export_MonSelEvent, 0xffd14d20)
NSTUB(eventproc_export_MemoryChecker, 0xffd14d24)
NSTUB(eventproc_export_VerifyByte, 0xffd14d28)
NSTUB(eventproc_export_EraseSignature, 0xffd14d2c)
NSTUB(eventproc_export_SDump, 0xffd14d3c)
NSTUB(eventproc_export_Dump, 0xffd14d40)
NSTUB(eventproc_export_Dump32, 0xffd14d50)
NSTUB(eventproc_export_Poke32, 0xffd14d64)
NSTUB(eventproc_export_Poke16, 0xffd14d74)
NSTUB(eventproc_export_Poke8, 0xffd14d84)
NSTUB(eventproc_export_Peek32, 0xffd14d94)
NSTUB(eventproc_export_Peek16, 0xffd14d98)
NSTUB(eventproc_export_Peek8, 0xffd14d9c)
NSTUB(eventproc_export_Wait, 0xffd14da0)

NSTUB(eventproc_export_ShowAllTaskInfo, 0xffd14db4)

NSTUB(eventproc_export_UI_ShowStateOfRecMode, 0xffd15678)

NSTUB(eventproc_export_UIFS_SetDialStillRec, 0xffd15784)
NSTUB(eventproc_export_UIFS_SetCaptureModeToP, 0xffd157a4)
NSTUB(eventproc_export_UIFS_SetDialMovieRec, 0xffd157e4)
NSTUB(eventproc_export_UIFS_SetDialPlay, 0xffd15824)
NSTUB(eventproc_export_UIFS_IsAvailableISO3200, 0xffd15844)
NSTUB(eventproc_export_UIFS_IsCurrentCaptureModeISO3200, 0xffd1584c)
NSTUB(eventproc_export_UIFS_SetCaptureModeToISO3200, 0xffd15868)
NSTUB(eventproc_export_UIFS_OpenPopupStrobe, 0xffd158c4)
NSTUB(eventproc_export_UIFS_ClosePopupStrobe, 0xffd158f4)
NSTUB(eventproc_export_UIFS_MountExtFlash, 0xffd15924)
NSTUB(eventproc_export_UIFS_UnmountExtFlash, 0xffd15954)
NSTUB(eventproc_export_UIFS_PressTeleButton, 0xffd15984)
NSTUB(eventproc_export_UIFS_UnpressTeleButton, 0xffd159c0)
NSTUB(eventproc_export_UIFS_PressWideButton, 0xffd159f8)
NSTUB(eventproc_export_UIFS_UnpressWideButton, 0xffd15a34)
NSTUB(eventproc_export_UIFS_ConnectVideo, 0xffd15a6c)
NSTUB(eventproc_export_UIFS_DisconnectVideo, 0xffd15a9c)
NSTUB(eventproc_export_UIFS_ConnectHDMI, 0xffd15acc)
NSTUB(eventproc_export_UIFS_DisconnectHDMI, 0xffd15ad0)
NSTUB(eventproc_export_UIFS_MoveZoomTo, 0xffd15ad4)
NSTUB(eventproc_export_UIFS_StopPostingUIEvent, 0xffd15ad8)
NSTUB(eventproc_export_UIFS_RestartPostingUIEvent, 0xffd15adc)
NSTUB(eventproc_export_UIFS_SetCaptureModeToTv, 0xffd15ae0)
NSTUB(eventproc_export_UIFS_SetCaptureModeToM, 0xffd15b14)
NSTUB(eventproc_export_UIFS_SetCaptureModeToMacro, 0xffd15b48)
NSTUB(eventproc_export_UIFS_PostModeDial, 0xffd15b50)
NSTUB(eventproc_export_UIFS_Capture, 0xffd15b78)
NSTUB(eventproc_export_UIFS_CaptureNoneStop, 0xffd15b7c)
NSTUB(eventproc_export_UIFS_StartMovieRecord, 0xffd15b80)
NSTUB(eventproc_export_UIFS_StopMovieRecord, 0xffd15b84)
NSTUB(eventproc_export_UIFS_StartClockMode, 0xffd15b88)
NSTUB(eventproc_export_UIFS_EndClockMode, 0xffd15b90)
NSTUB(eventproc_export_UIFS_SetCradleSetting, 0xffd15b98)
NSTUB(eventproc_export_UIFS_WriteFirmInfoToFile, 0xffd15b9c)
NSTUB(eventproc_export_UIFS_GetMovieRecoadableNumber, 0xffd15ba0)
NSTUB(eventproc_export_UIFS_GetStillShotableNumber, 0xffd15be8)
NSTUB(eventproc_export_UIFS_ChangeShootState, 0xffd15c1c)

NSTUB(eventproc_export_UIFS_ShootSeqToUI, 0xffd15c40)
NSTUB(eventproc_export_UIFS_GetLastPath, 0xffd15c48)
NSTUB(eventproc_export_UIFS_GetAvItemCount, 0xffd15c80)
NSTUB(eventproc_export_UIFS_GetTvItemCount, 0xffd15cd8)
NSTUB(eventproc_export_UIFS_GetAvItem, 0xffd15d30)
NSTUB(eventproc_export_UIFS_GetTvItem, 0xffd15d6c)
NSTUB(eventproc_export_UIFS_GetCurrentAvString, 0xffd15e68)
NSTUB(eventproc_export_UIFS_GetCurrentTvString, 0xffd15ee8)
NSTUB(eventproc_export_UIFS_IsAvailableShots, 0xffd15f68)
NSTUB(eventproc_export_UIFS_GetNumberOfDisplayedImage, 0xffd15f6c)

NSTUB(eventproc_export_EraseLogSector, 0xffd1c404)

NSTUB(eventproc_export_WriteToRom, 0xffd1cacc)
NSTUB(eventproc_export_EraseSectorOfRom, 0xffd1cb7c)

NSTUB(eventproc_export_FmtMenu_ExecuteQuickFormat, 0xffd2f74c)

NSTUB(eventproc_export_ExecuteResetFactoryWithRomWrite, 0xffd39b1c)

NSTUB(eventproc_export_memset, 0xffd90cf4)

NSTUB(eventproc_export_sscanf, 0xffd90e28)

