topdir=../../../../
OBJS=boot.o stubs_min.o stubs_auto.o stubs_entry.o stubs_entry_2.o capt_seq.o filewrite.o
#TODO lib.o movie_rec.o
STUBS_AUTO_DEPS=boot.c capt_seq.c filewrite.c
#TODO movie_rec.c

include $(topdir)platform/makefile_sub.inc

